<?php

return [
    'navigation' => ['title' => 'Ramadan Iftars', 'all' => 'All Iftars', 'approvals' => 'Planning approvals', 'monitoring_reviews' => 'Monitoring reviews'],
    'titles' => ['index' => 'Ramadan Iftars', 'show' => 'Ramadan Iftar workspace', 'guidance' => 'Ramadan Iftar guidance', 'create' => 'Create Ramadan Iftar', 'edit' => 'Edit Ramadan Iftar plan', 'execution' => 'Execution', 'monitoring' => 'Monitoring', 'monitoring_review' => 'Monitoring review', 'monitoring_review_queue' => 'Monitoring review queue'],
    'sections' => ['lifecycle' => 'Lifecycle', 'planning' => 'Planning', 'core' => 'Core planning', 'guidance' => 'Guidance', 'targeting' => 'Targeting', 'execution_needs' => 'Execution Needs', 'meals' => 'Meals', 'gifts' => 'Gifts', 'programs' => 'Program segments', 'teams' => 'Execution teams', 'volunteers' => 'Volunteers', 'supplies' => 'Supplies', 'attendance' => 'Attendance', 'approval' => 'Approval', 'workflow' => 'Workflow', 'monitoring' => 'Monitoring', 'closure' => 'Closure', 'actual_event' => 'Actual event data', 'reports' => 'Monitoring reports', 'verifications' => 'Field verifications'],
    'actions' => ['create' => 'Create Ramadan Iftar', 'edit' => 'Edit plan', 'submit' => 'Submit', 'resubmit' => 'Resubmit', 'approve' => 'Approve', 'return' => 'Return for correction', 'review_approval' => 'Review approval', 'start_execution' => 'Start execution', 'view_execution' => 'View execution', 'save_actual' => 'Save actual data', 'complete_execution' => 'Complete execution', 'monitoring' => 'Monitoring', 'create_report' => 'Create monitoring report', 'submit_monitoring' => 'Submit monitoring report', 'review_monitoring' => 'Review monitoring', 'save' => 'Save', 'back' => 'Back', 'accept_guidance' => 'Accept guidance and continue'],
    'statuses' => [
        'planning' => ['draft' => 'Draft', 'submitted' => 'Awaiting approval', 'changes_requested' => 'Returned for correction', 'approved' => 'Approved'],
        'execution' => ['planned' => 'Planned', 'pending' => 'Pending', 'cancelled' => 'Cancelled', 'in_progress' => 'In progress', 'completed' => 'Completed'],
        'monitoring' => ['draft' => 'Draft', 'submitted' => 'Awaiting review', 'returned' => 'Returned for correction', 'approved' => 'Approved'],
        'verification' => ['matched' => 'Matched', 'mismatched' => 'Mismatched', 'not_observed' => 'Not observed', 'not_applicable' => 'Not applicable'],
        'closure' => ['open' => 'Open', 'closed' => 'Closed'],
        'requirement' => ['required' => 'Required', 'not_required' => 'Not required'],
    ],
    'fields' => ['id' => 'ID', 'title' => 'Title', 'branch' => 'Branch', 'planned_date' => 'Planned date', 'actual_date' => 'Actual date', 'relations_officer' => 'Relations officer', 'planning_status' => 'Planning status', 'execution_status' => 'Execution status', 'monitoring_status' => 'Monitoring status', 'closure_status' => 'Closure status', 'expected' => 'Planned', 'actual' => 'Actual', 'variance' => 'Variance', 'current_step' => 'Current approval step', 'method' => 'Monitoring method', 'monitor' => 'Monitor', 'submitted_at' => 'Submitted at', 'observed_at' => 'Observed at', 'notes' => 'Notes', 'comment' => 'Review comment', 'field' => 'Field', 'verification_status' => 'Verification status', 'actions' => 'Actions', 'phone' => 'Phone', 'age' => 'Age', 'name' => 'Name'],
    'verification_fields' => ['attendance' => 'Attendance', 'meals' => 'Meals', 'date' => 'Event date', 'meal' => 'Meal: :name', 'gift' => 'Gift: :name', 'program' => 'Program: :name', 'team' => 'Team: :name', 'volunteer' => 'Volunteer requirement #:id', 'supply' => 'Supply: :name', 'execution_need' => 'Execution Need: :name'],
    'empty' => ['iftars' => 'No Ramadan Iftars are available.', 'meals' => 'No meals.', 'gifts' => 'No gifts.', 'programs' => 'No program segments.', 'teams' => 'No execution teams.', 'volunteers' => 'No volunteer requirements.', 'supplies' => 'No supplies.', 'monitoring' => 'No monitoring reports.', 'workflow' => 'No workflow history.', 'verifications' => 'No field verifications.', 'reviews' => 'No monitoring reports are awaiting review.'],
    'hints' => ['guidance_acceptance' => 'I have read and accept this guidance version.', 'version' => 'Version :number', 'read_only_execution' => 'Execution is completed and is shown read-only.', 'read_only_monitoring' => 'This monitoring evidence is read-only.', 'attendance_private' => 'Detailed attendee data is restricted to the execution workspace.', 'return_comment' => 'A comment is required when returning a report.', 'mismatch_documented' => 'Mismatches may be approved only when each mismatch has a monitoring note.'],
    'messages' => ['created' => 'Ramadan Iftar created.', 'updated' => 'Ramadan Iftar updated.', 'submitted' => 'Ramadan Iftar submitted for approval.', 'decision_recorded' => 'Approval decision recorded.', 'execution_started' => 'Ramadan Iftar execution started.', 'execution_updated' => 'Actual execution data saved.', 'execution_completed' => 'Ramadan Iftar execution completed.', 'monitoring_created' => 'Monitoring report created.', 'monitoring_updated' => 'Monitoring report updated.', 'monitoring_submitted' => 'Monitoring report submitted.', 'monitoring_reviewed' => 'Monitoring review decision recorded.', 'guidance_accepted' => 'Guidance accepted. You may create the Ramadan Iftar.'],
    'errors' => ['review_not_authorized' => 'You are not authorized to review this monitoring report.', 'review_submitted_only' => 'Only a submitted monitoring report may be reviewed.', 'self_review' => 'A monitor may not review their own report.', 'invalid_review_decision' => 'The monitoring review decision is invalid.', 'return_comment_required' => 'A return comment is required.', 'mismatch_note_required' => 'Every mismatched verification needs a note before approval.'],
];
