@php
$existing = $bazaar ?? null;
$tableRows = old('tables', $existing?->tables?->map(fn($t) => $t->toArray())->all() ?: [['table_number'=>1,'rental_type'=>'individual']]);
$selectedTargets = array_map('intval', old('target_group_ids', $existing?->targetGroupSelections?->pluck('target_group_id')->all() ?? []));
$selectedNeeds = collect(old('execution_needs', $existing?->executionNeeds?->map(function($n){$d=json_decode($n->planned_details,true) ?: [];return ['execution_need_type_id'=>$n->execution_need_type_id,'selected'=>1,'planned_details'=>is_array($d)?'':$n->planned_details]+$d;})->all() ?? []))->keyBy('execution_need_type_id');
@endphp
<div class="bazaar-form-shell">
@include('pages.events.bazaars._lifecycle', ['status' => $existing?->status ?? 'draft'])
@if($errors->any())<div class="alert alert-danger bazaar-validation-summary" tabindex="-1"><i class="fas fa-triangle-exclamation"></i> <strong>يرجى تصحيح الحقول التالية:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="card bazaar-section-card mb-4"><div class="card-header bazaar-section-head"><span class="bazaar-section-icon"><i class="fas fa-store"></i></span><div><strong><span>١</span> معلومات البازار</strong><small>الهوية الأساسية وموعد فتح السوق وإغلاقه.</small></div></div><div class="card-body row g-3">
<div class="col-md-6"><label class="form-label">اسم البازار</label><input required class="form-control" name="name" value="{{ old('name',$existing?->name) }}" placeholder="مثال: بازار المنتجات المحلية"></div>
<div class="col-md-2"><label class="form-label">تاريخ البازار</label><input required type="date" class="form-control" name="bazaar_date" value="{{ old('bazaar_date',$existing?->bazaar_date?->format('Y-m-d') ?? request('date')) }}"></div>
<div class="col-md-2"><label class="form-label">وقت البداية</label><input required type="time" class="form-control" name="starts_at" value="{{ old('starts_at',substr((string)$existing?->starts_at,0,5)) }}"></div>
<div class="col-md-2"><label class="form-label">وقت النهاية</label><input required type="time" class="form-control" name="ends_at" value="{{ old('ends_at',substr((string)$existing?->ends_at,0,5)) }}"></div></div></section>
<section class="card bazaar-section-card mb-4"><div class="card-header bazaar-section-head"><span class="bazaar-section-icon"><i class="fas fa-location-dot"></i></span><div><strong><span>٢</span> الموقع</strong><small>حدد مكان البازار وأضف تفاصيل واضحة للوصول.</small></div></div><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">مكان البازار</label><select class="form-select" name="location_type" data-location-type><option value="inside" @selected(old('location_type',$existing?->location_type)==='inside')>داخل المركز</option><option value="outside" @selected(old('location_type',$existing?->location_type)==='outside')>خارج المركز</option></select></div><div class="col-md-8"><label class="form-label" data-location-label>المكان داخل المركز / اسم الموقع</label><input required class="form-control" name="location_name" value="{{ old('location_name',$existing?->location_name) }}" placeholder="مثال: الساحة الرئيسية"></div><div class="col-md-8"><label class="form-label">العنوان / التفاصيل</label><textarea class="form-control" name="location_details" placeholder="اكتب تفاصيل الوصول والمكان">{{ old('location_details',$existing?->location_details) }}</textarea></div><div class="col-md-4"><label class="form-label">رابط الموقع على الخريطة (اختياري)</label><input type="url" class="form-control" name="map_url" value="{{ old('map_url',$existing?->map_url) }}" placeholder="https://maps.google.com/..."></div></div></section>
<section class="card bazaar-section-card mb-4"><div class="card-header bazaar-section-head"><span class="bazaar-section-icon"><i class="fas fa-people-group"></i></span><div><strong><span>٣</span> الفئات المستهدفة</strong><small>اختر الفئات من الدليل الموحد للفعاليات.</small></div></div><div class="card-body bazaar-target-grid">@foreach($targetGroups as $group)<label class="form-check"><input class="form-check-input" type="checkbox" name="target_group_ids[]" value="{{ $group->id }}" @checked(in_array($group->id,$selectedTargets))><span class="form-check-label">{{ $group->name }}</span></label>@endforeach</div></section>
<section class="card bazaar-section-card mb-4"><div class="card-header bazaar-section-head"><span class="bazaar-section-icon"><i class="fas fa-list-check"></i></span><div><strong><span>٤</span> احتياجات التنفيذ</strong><small>فعّل الاحتياج أولًا، ثم أكمل تفاصيله. الاحتياجات الإلزامية لا يمكن تعطيلها.</small></div></div><div class="card-body row g-3">@foreach($executionNeedTypes as $i=>$need)@php($row=$selectedNeeds->get($need->id,[]))<div class="col-lg-6"><div class="bazaar-need-card h-100"><input type="hidden" name="execution_needs[{{ $i }}][execution_need_type_id]" value="{{ $need->id }}"><label class="form-check fw-bold"><input class="form-check-input need-toggle" type="checkbox" name="execution_needs[{{ $i }}][selected]" value="1" @checked($need->isMandatoryForBazaar()||($row['selected']??false)) @disabled($need->isMandatoryForBazaar())>{{ $need->name }} @if($need->isMandatoryForBazaar())<span class="text-danger">(إلزامي)</span><input type="hidden" name="execution_needs[{{ $i }}][selected]" value="1">@endif</label><div class="need-details mt-2">@if($need->code==='invitations')<select class="form-select mb-2" name="execution_needs[{{ $i }}][invitation_type]"><option value="">نوع الدعوة</option><option value="paper" @selected(($row['invitation_type']??'')==='paper')>ورقية</option><option value="electronic" @selected(($row['invitation_type']??'')==='electronic')>إلكترونية</option></select><select class="form-select mb-2" name="execution_needs[{{ $i }}][distribution_channel]"><option value="">قناة التوزيع الإلكتروني</option><option value="whatsapp" @selected(($row['distribution_channel']??'')==='whatsapp')>واتساب</option><option value="sponsored_ad" @selected(($row['distribution_channel']??'')==='sponsored_ad')>إعلان ممول</option><option value="other" @selected(($row['distribution_channel']??'')==='other')>أخرى</option></select><input class="form-control" name="execution_needs[{{ $i }}][distribution_other]" value="{{ $row['distribution_other']??'' }}" placeholder="صف قناة التوزيع الأخرى">@else<textarea class="form-control" name="execution_needs[{{ $i }}][planned_details]" placeholder="اكتب تفاصيل الاحتياج">{{ $row['planned_details']??'' }}</textarea>@endif</div></div></div>@endforeach</div></section>
<section class="card bazaar-section-card mb-4"><div class="card-header bazaar-section-head bazaar-section-head--tables"><span class="bazaar-section-icon"><i class="fas fa-table-cells-large"></i></span><div class="flex-grow-1"><strong><span>٥</span> طاولات البازار</strong><small>يجب تعريف سجل مكتمل لكل طاولة مخططة، ويمكن طي البطاقات الطويلة.</small></div><div style="max-width:220px"><label>عدد طاولات البازار</label><input class="form-control" type="number" min="1" max="500" name="planned_table_count" data-table-count value="{{ old('planned_table_count',$existing?->planned_table_count ?? count($tableRows)) }}"></div></div><div class="card-body" data-tables>@foreach($tableRows as $i=>$table)@include('pages.events.bazaars._table_card',['i'=>$i,'table'=>$table])@endforeach</div></section>
<section class="card bazaar-section-card bazaar-review-card mb-4"><div class="card-header bazaar-section-head"><span class="bazaar-section-icon"><i class="fas fa-clipboard-check"></i></span><div><strong><span>٦</span> المراجعة والإرسال</strong><small>تأكد من اكتمال الأقسام والطاولات قبل المتابعة.</small></div></div><div class="card-body text-muted">راجع البيانات والطاولات ثم احفظ المسودة. يمكنك إرسالها للاعتماد من صفحة البازار.</div></section>
</div>
<template id="bazaar-table-template">@include('pages.events.bazaars._table_card',['i'=>'__INDEX__','table'=>[]])</template>
@push('styles')<link rel="stylesheet" href="{{ \App\Support\AssetVersion::url('assets/css/bazaar-form.css') }}">@endpush
@push('scripts')<script src="{{ asset('assets/js/bazaar-form.js') }}" defer></script>@endpush
