@extends('layouts.app')
@section('title','تنفيذ '.$bazaar->name)
@section('content')<div class="container-fluid" dir="rtl"><h1 class="h3">التنفيذ وما بعد التنفيذ — {{ $bazaar->name }}</h1><p class="text-muted">مسؤول العلاقات يؤكد القيم الفعلية لكل طاولة. الخصم لا يصبح نافذًا قبل اعتماد رئيس المركز.</p><form method="POST" action="{{ route('events.bazaars.execution.update',$bazaar) }}">@csrf @method('PUT')
@foreach($bazaar->tables as $i=>$table)<div class="card mb-3"><div class="card-header"><strong>الطاولة رقم {{ $table->table_number }}</strong></div><div class="card-body row g-3"><input type="hidden" name="tables[{{ $i }}][id]" value="{{ $table->id }}">
<div class="col-md-4"><label class="form-label">هل تم حجز الطاولة؟</label><select class="form-select" name="tables[{{ $i }}][was_booked]"><option value="1" @selected($table->was_booked===true)>نعم</option><option value="0" @selected($table->was_booked===false)>لا</option></select></div><div class="col-md-4"><label class="form-label">هل المستأجر الفعلي مطابق؟</label><select class="form-select" name="tables[{{ $i }}][actual_renter_matches]"><option value="1" @selected($table->actual_renter_matches!==false)>مطابق</option><option value="0" @selected($table->actual_renter_matches===false)>متغير</option></select></div><div class="col-md-4"><label class="form-label">سبب/ملاحظة تغيير المستأجر</label><input class="form-control" name="tables[{{ $i }}][renter_change_note]" value="{{ $table->renter_change_note }}" placeholder="مطلوب عند تغيير المستأجر"></div>
<div class="col-md-4"><label class="form-label">اسم المستأجر الفعلي</label><input class="form-control" name="tables[{{ $i }}][actual_tenant_name]" value="{{ $table->actual_tenant_name }}" placeholder="مثال: أحمد محمد"></div><div class="col-md-4"><label class="form-label">هاتف المستأجر الفعلي</label><input class="form-control" name="tables[{{ $i }}][actual_tenant_phone]" value="{{ $table->actual_tenant_phone }}" placeholder="مثال: 07XXXXXXXX"></div><div class="col-md-4"><label class="form-label">رقم الجهة الفعلية (عند التغيير)</label><input type="number" class="form-control" name="tables[{{ $i }}][actual_community_organization_id]" value="{{ $table->actual_community_organization_id }}"></div>
<div class="col-md-6"><label class="form-label">وصف المادة المخطط</label><div class="form-control bg-light">{{ $table->planned_material_description }}</div></div><div class="col-md-6"><label class="form-label">وصف المادة الفعلية</label><textarea class="form-control" name="tables[{{ $i }}][actual_material_description]" placeholder="اكتب وصف المادة الفعلية">{{ $table->actual_material_description }}</textarea></div><div class="col-md-4"><label class="form-label">المادة مطابقة؟</label><select class="form-select" name="tables[{{ $i }}][material_matches]"><option value="1" @selected($table->material_matches!==false)>مطابق</option><option value="0" @selected($table->material_matches===false)>غير مطابق</option></select></div><div class="col-md-8"><label class="form-label">سبب عدم المطابقة</label><input class="form-control" name="tables[{{ $i }}][material_mismatch_note]" value="{{ $table->material_mismatch_note }}" placeholder="مطلوب عند عدم المطابقة"></div>
<div class="col-md-3"><label class="form-label">الإيجار المخطط</label><div class="form-control bg-light">{{ $table->planned_rental_amount }}</div></div><div class="col-md-3"><label class="form-label">هل تم الدفع؟</label><select class="form-select" name="tables[{{ $i }}][is_paid]"><option value="0">لا</option><option value="1" @selected($table->is_paid)>نعم</option></select></div><div class="col-md-3"><label class="form-label">المبلغ المدفوع</label><input type="number" min="0" step=".01" class="form-control" name="tables[{{ $i }}][amount_paid]" value="{{ $table->amount_paid }}" placeholder="مثال: 25.00"></div><div class="col-md-3"><label class="form-label">حالة الدفع</label><select class="form-select" name="tables[{{ $i }}][payment_status]"><option value="unpaid">غير مدفوع</option><option value="partial" @selected($table->payment_status==='partial')>مدفوع جزئيًا</option><option value="paid" @selected($table->payment_status==='paid')>مدفوع بالكامل</option><option value="approved_discount" @selected($table->payment_status==='approved_discount')>خصم معتمد</option></select></div>
@if(!$table->currentDiscount || in_array($table->currentDiscount->status,['returned','rejected']))<div class="col-12 border-top pt-3"><strong>طلب خصم (اختياري)</strong><div class="row g-2 mt-1"><div class="col-md-3"><select class="form-select" name="tables[{{ $i }}][discount_type]"><option value="">بدون خصم</option><option value="amount">مبلغ</option><option value="percentage">نسبة</option></select></div><div class="col-md-3"><input type="number" min="0" step=".01" class="form-control" name="tables[{{ $i }}][discount_value]" placeholder="قيمة الخصم"></div><div class="col-md-6"><input class="form-control" name="tables[{{ $i }}][discount_reason]" placeholder="سبب الخصم"></div></div></div>@elseif($table->currentDiscount->status==='pending')<div class="col-12"><div class="alert alert-warning">بانتظار موافقة رئيس الفرع على الخصم</div></div>@endif
<div class="col-12"><label class="form-label">ملاحظات فعلية</label><textarea class="form-control" name="tables[{{ $i }}][actual_notes]" placeholder="اكتب أي ملاحظات إضافية">{{ $table->actual_notes }}</textarea></div></div></div>@endforeach
<button class="btn btn-outline-primary">حفظ التنفيذ</button> <button class="btn btn-success" name="complete" value="1">إرسال ما بعد التنفيذ للمتابعة</button></form></div>@endsection
