@extends('layouts.app')
@section('title',$bazaar->name)
@section('content')
<div class="container-fluid" dir="rtl"><div class="d-flex justify-content-between mb-4"><div><h1 class="h3">{{ $bazaar->name }}</h1><p class="text-muted">{{ $bazaar->bazaar_date?->format('Y-m-d') }} · {{ $bazaar->location_name }} · الحالة: {{ __('bazaars.statuses.'.$bazaar->status) }}</p></div><div class="d-flex gap-2">@if($bazaar->isPlanningEditable())@can('bazaars.edit')<a class="btn btn-outline-primary" href="{{ route('events.bazaars.edit',$bazaar) }}">تعديل</a>@endcan @can('bazaars.submit')<form method="POST" action="{{ route('events.bazaars.submit',$bazaar) }}">@csrf<button class="btn btn-primary">إرسال للاعتماد</button></form>@endcan@endif @if(in_array($bazaar->status,['approved','executing']))@can('bazaars.execute')<a class="btn btn-success" href="{{ route('events.bazaars.execution',$bazaar) }}">التنفيذ وما بعده</a>@endcan@endif</div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h6">التخطيط</h2><dl><dt>الوقت</dt><dd>{{ $bazaar->starts_at }} - {{ $bazaar->ends_at }}</dd><dt>الموقع</dt><dd>{{ $bazaar->location_type==='inside'?'داخل المركز':'خارج المركز' }} — {{ $bazaar->location_details }}</dd><dt>مسؤول العلاقات</dt><dd>{{ $bazaar->relationsOfficer?->name }}</dd></dl></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h6">الفئات المستهدفة</h2>@foreach($bazaar->targetGroupSelections as $selection)<span class="badge bg-light text-dark">{{ $selection->targetGroup?->name }}</span>@endforeach</div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h6">احتياجات التنفيذ</h2>@foreach($bazaar->executionNeeds as $need)<div>{{ $need->executionNeedType?->name }}: {{ $need->planned_details }}</div>@endforeach</div></div></div></div>
@can('bazaars.approve')@if($bazaar->status==='submitted')<div class="card mb-3"><div class="card-body"><h2 class="h5">اعتماد رئيس المركز</h2><form method="POST" action="{{ route('events.bazaars.decision',$bazaar) }}">@csrf<textarea name="note" class="form-control mb-2" placeholder="ملاحظة القرار"></textarea><button name="decision" value="approve" class="btn btn-success">اعتماد</button> <button name="decision" value="return" class="btn btn-warning">إعادة</button> <button name="decision" value="reject" class="btn btn-danger">رفض</button></form></div></div>@endif @endcan
<div class="card"><div class="card-header"><strong>الطاولات: مخطط {{ $bazaar->planned_table_count }} / مشغول فعليًا {{ $bazaar->actual_occupied_table_count ?? '—' }}</strong></div><div class="card-body">@foreach($bazaar->tables as $table)<div class="border rounded p-3 mb-3"><h3 class="h6">الطاولة رقم {{ $table->table_number }}</h3><div class="row"><div class="col-md-4"><strong>المستأجر المخطط:</strong> {{ $table->rental_type==='individual'?$table->tenant_name:$table->organization?->name }}</div><div class="col-md-4"><strong>المادة المخططة:</strong> {{ $table->planned_material_description }}</div><div class="col-md-4"><strong>الإيجار المخطط:</strong> {{ $table->planned_rental_amount }}</div>@if($table->was_booked!==null)<div class="col-12 mt-2 bg-light p-2"><strong>الفعلي:</strong> {{ $table->was_booked?'محجوزة':'غير محجوزة' }} | المستأجر {{ $table->actual_renter_matches?'مطابق':'متغير' }} | المادة {{ $table->material_matches?'مطابقة':'غير مطابقة' }} | المدفوع {{ $table->amount_paid ?? 0 }} / المستحق {{ $table->amount_due }}</div>@endif</div>
@if($table->currentDiscount)<div class="alert {{ $table->currentDiscount->status==='pending'?'alert-warning':'alert-info' }} mt-2">الخصم: {{ $table->currentDiscount->discount_value }} ({{ __('bazaars.discount_statuses.'.$table->currentDiscount->status) }}) @if($table->currentDiscount->status==='pending') بانتظار موافقة رئيس الفرع على الخصم @endif
@can('bazaars.discount_review')@if($table->currentDiscount->status==='pending')<form class="mt-2" method="POST" action="{{ route('events.bazaars.discounts.decision',$table->currentDiscount) }}">@csrf<input name="decision_note" class="form-control mb-2" placeholder="ملاحظة القرار"><button class="btn btn-sm btn-success" name="decision" value="approve">اعتماد</button> <button class="btn btn-sm btn-warning" name="decision" value="return">إعادة</button> <button class="btn btn-sm btn-danger" name="decision" value="reject">رفض</button></form>@endif @endcan</div>@endif</div>@endforeach</div></div>
@can('bazaars.monitor')@if($bazaar->status==='post_execution')<div class="card mt-3"><div class="card-body"><h2 class="h5">متابعة ومطابقة المخطط بالفعلي</h2><p>راجع بيانات البازار والطاولات أعلاه دون إعادة إدخال القيم الفعلية.</p><form method="POST" action="{{ route('events.bazaars.verify',$bazaar) }}">@csrf<textarea class="form-control mb-2" name="verification_note" placeholder="ملاحظات المتابعة والتحقق"></textarea><button class="btn btn-primary" name="decision" value="verify">تحقق وإرسال للاعتماد النهائي</button> <button class="btn btn-warning" name="decision" value="return">إعادة للعلاقات</button></form></div></div>@endif @endcan
@can('bazaars.close')@if($bazaar->status==='verified')<div class="card mt-3"><div class="card-body"><h2 class="h5">الاعتماد النهائي</h2><p>أكمل مسؤول المتابعة التحقق. راجع النتيجة قبل الإغلاق.</p><form method="POST" action="{{ route('events.bazaars.close',$bazaar) }}">@csrf<button class="btn btn-success">اعتماد نهائي وإغلاق</button></form></div></div>@endif @endcan</div>
@endsection
