@extends('layouts.app')
@section('title', __('evaluation.followup.sidebar.dashboard'))
@push('styles')<style>
.fu-page{--fu:#2563eb;--fu-soft:#eff6ff}.fu-hero{background:linear-gradient(135deg,#172554,#1d4ed8 65%,#38bdf8);color:#fff;border:0;border-radius:24px;overflow:hidden}.fu-action{border:1px solid rgba(255,255,255,.28);background:rgba(255,255,255,.12);color:#fff}.fu-stat{border:0;border-radius:18px;box-shadow:0 8px 28px rgba(15,23,42,.07);transition:.2s}.fu-stat:hover{transform:translateY(-2px)}.fu-stat-icon{width:44px;height:44px;display:grid;place-items:center;border-radius:14px;background:var(--fu-soft);color:var(--fu)}.fu-workflow{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.fu-step{padding:16px 10px;border-radius:16px;background:#f8fafc;text-align:center;position:relative}.fu-step strong{display:block;font-size:1.45rem;color:#1d4ed8}.fu-panel{border:0;border-radius:20px;box-shadow:0 8px 28px rgba(15,23,42,.06)}.fu-score{font-weight:800;color:#1d4ed8;background:#eff6ff;border-radius:999px;padding:.35rem .7rem}@media(max-width:991px){.fu-workflow{grid-template-columns:repeat(2,1fr)}}
</style>@endpush
@section('content')
<div class="container-fluid py-4 fu-page">
 <section class="card fu-hero mb-4"><div class="card-body p-4 p-lg-5"><div class="row align-items-center g-4"><div class="col-lg-7"><div class="opacity-75 mb-2">{{ __('evaluation.followup.current_date') }} · {{ now()->translatedFormat('l، j F Y') }}</div><h1 class="display-6 fw-bold">{{ __('evaluation.followup.welcome',['name'=>$user->name]) }}</h1><p class="fs-5 mb-2">{{ __('evaluation.followup.role_branch',['branch'=>$user->branch?->city ?: $user->branch?->name]) }}</p><p class="opacity-75 mb-0">{{ __('evaluation.followup.summary') }}</p></div><div class="col-lg-5"><div class="d-flex flex-wrap gap-2 justify-content-lg-end"><a class="btn fu-action" href="{{ route('followup.monthly-plans') }}"><i class="fas fa-calendar-days me-1"></i>{{ __('evaluation.followup.sidebar.monthly_plans') }}</a><a class="btn fu-action" href="{{ route('followup.awaiting-evaluation') }}"><i class="fas fa-hourglass-half me-1"></i>{{ __('evaluation.followup.sidebar.awaiting_evaluation') }}</a><a class="btn fu-action" href="{{ route('followup.evaluations.index') }}"><i class="fas fa-clipboard-check me-1"></i>{{ __('evaluation.followup.sidebar.previous_evaluations') }}</a></div></div></div></div></section>
 @php($cards=[['month_plans','plans_this_month','fa-calendar',route('followup.monthly-plans')],['post_completed','post_completed','fa-circle-check',route('followup.awaiting-evaluation')],['awaiting_verification','awaiting_review','fa-magnifying-glass',route('followup.awaiting-evaluation')],['ready_evaluation','ready_evaluation','fa-clipboard-check',route('followup.awaiting-evaluation')],['evaluated_month','evaluated_this_month','fa-award',route('followup.evaluations.index')],['branch_average','branch_average','fa-chart-line',route('followup.evaluations.index')]])
 <div class="row g-3 mb-4">@foreach($cards as $card)<div class="col-sm-6 col-xl-2"><a href="{{ $card[3] }}" class="text-decoration-none text-reset"><div class="card fu-stat h-100"><div class="card-body"><div class="fu-stat-icon mb-3"><i class="fas {{ $card[2] }}"></i></div><div class="h3 fw-bold mb-1">{{ $stats[$card[0]] }}{{ $card[0]==='branch_average' ? '/10' : '' }}</div><div class="text-muted small">{{ __('evaluation.followup.'.$card[1]) }}</div></div></div></a></div>@endforeach</div>
 <div class="card fu-panel mb-4"><div class="card-body"><div class="d-flex justify-content-between mb-3"><h2 class="h5 fw-bold">{{ __('evaluation.followup.workflow') }}</h2></div><div class="fu-workflow">@foreach(['planned'=>'الخطط الشهرية','executed'=>'تم التنفيذ','post_completed'=>'تم إكمال ما بعد التنفيذ','awaiting_review'=>'بانتظار المراجعة','ready'=>'جاهز للتقييم','evaluated'=>'تم التقييم'] as $key=>$label)<div class="fu-step"><strong>{{ $workflow[$key] }}</strong><span>{{ $label }}</span></div>@endforeach</div></div></div>
 <div class="row g-4"><div class="col-xl-7"><div class="card fu-panel h-100"><div class="card-header bg-transparent d-flex justify-content-between"><h2 class="h5 fw-bold mb-0">{{ __('evaluation.followup.needs_action') }}</h2><a href="{{ route('followup.awaiting-evaluation') }}">{{ __('evaluation.followup.all') }}</a></div><div class="list-group list-group-flush">@forelse($urgent as $activity)<div class="list-group-item py-3"><div class="d-flex justify-content-between gap-3"><div><strong>{{ $activity->title }}</strong><div class="small text-muted">{{ optional($activity->proposed_date)->translatedFormat('d M Y') }} · {{ $activity->responsible_party ?: '—' }}</div><div class="mt-1"><span class="badge bg-warning-subtle text-warning-emphasis">{{ $activity->pending_count }} {{ __('evaluation.followup.awaiting_review') }}</span>@if($activity->incorrect_count)<span class="badge bg-danger-subtle text-danger-emphasis">{{ $activity->incorrect_count }} {{ __('evaluation.statuses.incorrect') }}</span>@endif</div></div><a class="btn btn-sm btn-outline-primary align-self-center" href="{{ route('evaluations.verification.review',$activity) }}">{{ __('evaluation.followup.review') }}</a></div></div>@empty<div class="p-5 text-center text-muted">{{ __('evaluation.followup.no_results') }}</div>@endforelse</div></div></div>
 <div class="col-xl-5"><div class="card fu-panel h-100"><div class="card-header bg-transparent d-flex justify-content-between"><h2 class="h5 fw-bold mb-0">{{ __('evaluation.followup.recent_evaluations') }}</h2><a href="{{ route('followup.evaluations.index') }}">{{ __('evaluation.followup.all') }}</a></div><div class="card-body">@forelse($recentEvaluations as $evaluation)<div class="d-flex justify-content-between align-items-center border-bottom py-3"><div><strong>{{ $evaluation->activity?->title }}</strong><div class="small text-muted">{{ optional($evaluation->submitted_at)->translatedFormat('d M Y') }} · {{ $evaluation->evaluator?->name }}</div></div><a href="{{ route('evaluations.show',$evaluation) }}" class="fu-score">{{ rtrim(rtrim(number_format($evaluation->normalized_score,2),'0'),'.') }}/10</a></div>@empty<div class="py-5 text-center text-muted">{{ __('evaluation.followup.no_results') }}</div>@endforelse</div></div></div></div>
 <div class="row g-4 mt-1"><div class="col-xl-8"><div class="card fu-panel"><div class="card-header bg-transparent d-flex justify-content-between"><h2 class="h5 fw-bold mb-0">{{ __('evaluation.followup.monthly_plans') }}</h2><a href="{{ route('followup.monthly-plans') }}">{{ __('evaluation.followup.view_full_calendar') }}</a></div><div class="card-body row g-3">@forelse($upcoming as $activity)<div class="col-md-6"><div class="border rounded-3 p-3"><strong>{{ $activity->title }}</strong><div class="small text-muted">{{ optional($activity->proposed_date)->translatedFormat('d M') }} · {{ optional($activity->time_from)->format('H:i') ?: '—' }}</div></div></div>@empty<div class="text-center text-muted py-4">{{ __('evaluation.followup.no_results') }}</div>@endforelse</div></div></div><div class="col-xl-4"><div class="card fu-panel"><div class="card-header bg-transparent"><h2 class="h5 fw-bold mb-0">{{ __('evaluation.followup.branch_performance') }}</h2></div><div class="card-body">@foreach(['correct','incorrect','pending'] as $state)<div class="d-flex justify-content-between py-2"><span>{{ __('evaluation.statuses.'.$state) }}</span><strong>{{ $verificationSummary[$state] ?? 0 }}</strong></div>@endforeach</div></div></div></div>
</div>
@endsection
