@php
$value = fn (string $field, $default = '') => old($field, data_get($ramadanIftar, $field, $default));
$needsAreConfigured = $executionNeedTypes->isNotEmpty();
$selectedHostType = $value('host_type');
$collections = [
    'attendees' => old('attendees', $ramadanIftar ? $ramadanIftar->attendees->toArray() : [[]]),
    'target_groups' => old('target_groups', $ramadanIftar ? $ramadanIftar->targetGroupSelections->toArray() : [[]]),
    'meals' => old('meals', $ramadanIftar ? $ramadanIftar->meals->map(fn ($meal) => array_merge($meal->toArray(), ['items' => $meal->items->toArray()]))->toArray() : [['items' => [[]]]]),
    'gifts' => old('gifts', $ramadanIftar ? $ramadanIftar->gifts->toArray() : [[]]),
    'program_segments' => old('program_segments', $ramadanIftar ? $ramadanIftar->programSegments->toArray() : [[]]),
    'execution_teams' => old('execution_teams', $ramadanIftar ? $ramadanIftar->executionTeams->map(fn ($team) => array_merge($team->toArray(), ['members' => $team->members->toArray()]))->toArray() : [['members' => [[]]]]),
    'volunteer_requirements' => old('volunteer_requirements', $ramadanIftar ? $ramadanIftar->volunteerRequirements->toArray() : [[]]),
    'supplies' => old('supplies', $ramadanIftar ? $ramadanIftar->supplies->toArray() : [[]]),
    'execution_needs' => old('execution_needs', $ramadanIftar ? $ramadanIftar->executionNeeds->toArray() : []),
];
@endphp
<div class="container py-4">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('events.ramadan.iftars.index') }}">{{ __('ramadan_iftars.navigation.title') }}</a></li><li class="breadcrumb-item active" aria-current="page">{{ __($ramadanIftar ? 'ramadan_iftars.titles.edit' : 'ramadan_iftars.titles.create') }}</li></ol></nav>
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1 class="h3 mb-1">{{ __('ramadan_iftars.titles.'.($ramadanIftar ? 'edit' : 'create')) }}</h1>@unless($needsAreConfigured)<p class="text-muted mb-0">{{ __('ramadan_iftars.bootstrap.execution_needs') }}</p>@endunless</div>@if($ramadanIftar)<a class="btn btn-outline-secondary" href="{{ route('events.ramadan.iftars.show',$ramadanIftar) }}">{{ __('ramadan_iftars.actions.back') }}</a>@endif</div>
    @if($errors->any())<div class="alert alert-danger" role="alert"><strong>يرجى مراجعة الحقول التالية:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @forelse($ramadanPeriods as $period)<div class="alert alert-light border"><i class="fas fa-calendar-check text-success"></i> فترة رمضان المعتمدة ({{ $period->year }} ميلادي): <strong>{{ $period->start_date->format('Y-m-d') }}</strong> — <strong>{{ $period->end_date->format('Y-m-d') }}</strong></div>@empty<div class="alert alert-warning">لا توجد فترة رمضان فعالة. لا يمكن حفظ تاريخ إفطار حتى تضبطها الإدارة.</div>@endforelse
    <nav class="ramadan-section-nav d-flex flex-wrap gap-2 mb-3" aria-label="أقسام النموذج"><a class="btn btn-sm btn-outline-primary" href="#iftar-basic">البيانات الأساسية</a><a class="btn btn-sm btn-outline-primary" href="#iftar-location">الموقع والجهة</a><a class="btn btn-sm btn-outline-primary" href="#iftar-needs">احتياجات التنفيذ</a><a class="btn btn-sm btn-outline-primary" href="#iftar-targets">المستفيدون</a></nav>
    <form method="POST" action="{{ $formAction }}" id="ramadan-planning-form">@csrf @if($formMethod !== 'POST') @method($formMethod) @endif
        <div class="alert alert-success"><i class="fas fa-check-circle"></i> تم إقرار نسخة الإرشادات الحالية قبل بدء هذا النموذج. <a href="{{ route('events.ramadan.guidance.show') }}">عرض الإرشادات</a></div>
        <div class="card shadow-sm mb-3" id="iftar-basic"><div class="card-header fw-semibold"><i class="fas fa-circle-info text-success"></i> {{ __('ramadan_iftars.planning.basic_information') }}</div><div class="card-body row g-3">
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.agenda_event') }}</label><select class="form-select" name="agenda_event_id"><option value="">{{ __('ramadan_iftars.options.none') }}</option>@foreach($agendaEvents as $event)<option value="{{ $event->id }}" {{ $value('agenda_event_id') == $event->id ? 'selected' : '' }}>{{ $event->event_name }}</option>@endforeach</select></div>
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.fields.title') }}</label><input class="form-control" name="title" value="{{ $value('title') }}" required></div>
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.description') }}</label><input class="form-control" name="description" value="{{ $value('description') }}"></div>
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.fields.relations_officer') }}</label><select class="form-select" name="relations_officer_id" required>@foreach($users as $user)<option value="{{ $user->id }}" {{ $value('relations_officer_id') == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>@endforeach</select></div>
            <div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.fields.planned_date') }} <span class="text-danger">*</span></label><input type="date" class="form-control @error('planned_date') is-invalid @enderror" name="planned_date" value="{{ old('planned_date',optional($ramadanIftar?->planned_date)->format('Y-m-d')) }}" required aria-describedby="planned-date-error">@error('planned_date')<div class="invalid-feedback" id="planned-date-error">{{ $message }}</div>@enderror</div>
            <div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.labels.time_from') }}</label><input type="time" class="form-control" name="time_from" value="{{ $value('time_from') }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.labels.time_to') }}</label><input type="time" class="form-control" name="time_to" value="{{ $value('time_to') }}"></div>
        </div></div>
        <div class="card shadow-sm mb-3" id="iftar-location"><div class="card-header fw-semibold"><i class="fas fa-location-dot text-success"></i> {{ __('ramadan_iftars.planning.location_host') }}</div><div class="card-body row g-3">
            <div class="col-md-4"><label class="form-label">{{ __('ramadan_iftars.labels.location_type') }}</label><select class="form-select" name="location_type">@foreach($locationTypes as $type)<option value="{{ $type }}" {{ $value('location_type') === $type ? 'selected' : '' }}>{{ __('ramadan_iftars.options.'.$type) }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">{{ __('ramadan_iftars.labels.host_type') }} <span class="text-danger">*</span></label><select class="form-select @error('host_type') is-invalid @enderror" name="host_type">@foreach($hostTypes as $type)<option value="{{ $type }}" {{ $selectedHostType === $type ? 'selected' : '' }}>{{ __('ramadan_iftars.options.'.$type) }}</option>@endforeach</select>@error('host_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label">{{ __('ramadan_iftars.labels.location_name') }} <span class="text-danger">*</span></label><input class="form-control @error('location_name') is-invalid @enderror" name="location_name" value="{{ $value('location_name') }}">@error('location_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.address') }}</label><input class="form-control" name="address" value="{{ $value('address') }}"></div><div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.google_maps_url') }}</label><input class="form-control" name="google_maps_url" value="{{ $value('google_maps_url') }}"></div>
            <div class="col-md-6 position-relative">@include('pages.events.ramadan._reference_picker', ['field' => 'community_organization_id', 'label' => __('ramadan_iftars.labels.community_organization'), 'selected' => $selectedCommunityOrganization, 'searchUrl' => route('events.ramadan.iftars.references.organizations.index'), 'createUrl' => route('events.ramadan.iftars.references.organizations.store')])</div>
            <div class="col-md-6 position-relative">@include('pages.events.ramadan._reference_picker', ['field' => 'local_community_id', 'label' => __('ramadan_iftars.labels.local_community'), 'selected' => $selectedLocalCommunity, 'searchUrl' => route('events.ramadan.iftars.references.local-communities.index'), 'createUrl' => route('events.ramadan.iftars.references.local-communities.store')])</div>
            @foreach(['contact_name','contact_phone','supporting_entity_name'] as $field)<div class="col-md-4"><label class="form-label">{{ __('ramadan_iftars.labels.'.$field) }} @if(in_array($field, ['contact_name','contact_phone'], true))<span class="text-danger">*</span>@endif</label><input class="form-control @error($field) is-invalid @enderror" name="{{ $field }}" value="{{ $value($field) }}">@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endforeach
            <div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.mobilization_method') }} <span class="text-danger">*</span></label><select class="form-select @error('mobilization_method_id') is-invalid @enderror" name="mobilization_method_id"><option value="">{{ __('ramadan_iftars.options.none') }}</option>@foreach($mobilizationMethods as $item)<option value="{{ $item->id }}" {{ $value('mobilization_method_id') == $item->id ? 'selected' : '' }}>{{ app()->getLocale()==='ar' ? $item->name_ar : ($item->name_en ?: $item->name_ar) }}</option>@endforeach</select>@error('mobilization_method_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">{{ __('ramadan_iftars.labels.mobilization_method_other') }}</label><input class="form-control @error('mobilization_method_other') is-invalid @enderror" name="mobilization_method_other" value="{{ $value('mobilization_method_other') }}">@error('mobilization_method_other')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        </div></div>
        <div class="card shadow-sm mb-3" data-repeat="attendees" data-attendance-section><div class="card-header d-flex justify-content-between"><strong>كشف حضور المجتمع المحلي</strong><button type="button" class="btn btn-sm btn-outline-primary add-row">إضافة</button></div><div class="card-body">@foreach($collections['attendees'] as $i=>$row)<div class="planning-row border rounded p-3 mb-2"><div class="d-flex justify-content-between"><strong>السطر {{ $i+1 }}</strong><button type="button" class="btn btn-sm btn-outline-danger remove-row" aria-label="حذف السطر {{ $i+1 }}">حذف</button></div><input type="hidden" name="attendees[{{ $i }}][id]" value="{{ $row['id']??'' }}"><div class="row g-2 mt-1"><div class="col-md-5"><label class="form-label">الاسم</label><input class="form-control" name="attendees[{{ $i }}][full_name]" value="{{ $row['full_name']??'' }}"></div><div class="col-md-4"><label class="form-label">الهاتف</label><input class="form-control" name="attendees[{{ $i }}][phone]" value="{{ $row['phone']??'' }}"></div><div class="col-md-3"><label class="form-label">العمر</label><input type="number" min="0" max="120" class="form-control" name="attendees[{{ $i }}][age]" value="{{ $row['age']??'' }}"></div></div></div>@endforeach</div></div>
        @php $rows=$collections['target_groups']; @endphp
        <div class="card shadow-sm mb-3" data-repeat="target_groups" id="iftar-targets"><div class="card-header d-flex justify-content-between align-items-center"><strong>{{ __('ramadan_iftars.sections.targeting') }}</strong><button type="button" class="btn btn-sm btn-outline-primary add-row">{{ __('ramadan_iftars.planning.add') }}</button></div><div class="card-body">@foreach($rows as $i=>$row)<div class="planning-row border rounded p-3 mb-3"><div class="d-flex justify-content-between mb-2"><strong>{{ __('ramadan_iftars.planning.row',['number'=>$i+1]) }}</strong><button type="button" class="btn btn-sm btn-outline-danger remove-row">{{ __('ramadan_iftars.planning.remove') }}</button></div><input type="hidden" name="target_groups[{{ $i }}][id]" value="{{ $row['id']??'' }}"><div class="row g-3"><div class="col-md-3"><label class="form-label">{{ __('ramadan_iftars.labels.target_group') }}</label><select class="form-select" name="target_groups[{{ $i }}][target_group_id]">@foreach($targetGroups as $item)<option value="{{ $item->id }}" {{ ($row['target_group_id'] ?? null) == $item->id ? 'selected' : '' }}>{{ $item->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">{{ __('ramadan_iftars.labels.beneficiary_segment') }}</label><select class="form-select" name="target_groups[{{ $i }}][beneficiary_segment_id]"><option value="">{{ __('ramadan_iftars.options.none') }}</option>@foreach($beneficiarySegments as $item)<option value="{{ $item->id }}" {{ ($row['beneficiary_segment_id'] ?? null) == $item->id ? 'selected' : '' }}>{{ app()->getLocale()==='ar'?$item->name_ar:($item->name_en?:$item->name_ar) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.labels.planned_count') }}</label><input class="form-control" type="number" min="0" name="target_groups[{{ $i }}][planned_count]" value="{{ $row['planned_count']??0 }}"></div><div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.labels.other_group') }}</label><input class="form-control" name="target_groups[{{ $i }}][target_group_custom_text]" value="{{ $row['target_group_custom_text']??'' }}"></div><div class="col-md-2"><label class="form-label">{{ __('ramadan_iftars.labels.other_segment') }}</label><input class="form-control" name="target_groups[{{ $i }}][segment_custom_text]" value="{{ $row['segment_custom_text']??'' }}"></div></div></div>@endforeach</div></div>
        @include('pages.events.ramadan._planning_collections', ['collections'=>$collections,'mealItemTypes'=>$mealItemTypes,'users'=>$users,'beneficiarySegments'=>$beneficiarySegments,'collectionFilter'=>[],'includeMeals'=>true])
        <div class="card shadow-sm mb-3" id="iftar-needs"><div class="card-header fw-semibold d-flex justify-content-between"><span><i class="fas fa-list-check text-success"></i> {{ __('ramadan_iftars.sections.execution_needs') }}</span><span class="badge bg-primary" data-selected-needs-count>0 احتياجات مفعّلة</span></div><div class="card-body"><div class="ramadan-needs-grid">
        @forelse($executionNeedTypes as $needType) @php $selectedNeed=collect($collections['execution_needs'])->firstWhere('execution_need_type_id',$needType->id); $mandatory=$needType->isMandatoryForRamadan(); $enabled=$mandatory || (bool) ($selectedNeed['is_required'] ?? false); @endphp
            <div class="ramadan-need-option {{ $enabled?'is-active':'' }}">@if($selectedNeed)<input type="hidden" name="execution_needs[{{ $needType->id }}][id]" value="{{ $selectedNeed['id']??'' }}">@endif<input type="hidden" name="execution_needs[{{ $needType->id }}][execution_need_type_id]" value="{{ $needType->id }}"><input type="hidden" name="execution_needs[{{ $needType->id }}][is_required]" value="0"><div class="d-flex justify-content-between align-items-center gap-2"><div><label class="form-check-label fw-semibold" for="need-{{ $needType->id }}">{{ $needType->name }}</label> <span class="badge {{ $mandatory ? 'bg-danger' : 'bg-light text-dark border' }}">{{ $mandatory ? 'إجباري' : 'اختياري' }}</span> <span class="badge bg-success" data-enabled-badge {{ $enabled ? '' : 'hidden' }}>مفعّل</span></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" data-ramadan-need-toggle data-mandatory="{{ $mandatory ? '1' : '0' }}" name="execution_needs[{{ $needType->id }}][is_required]" value="1" id="need-{{ $needType->id }}" {{ $enabled ? 'checked' : '' }} {{ $mandatory ? 'disabled' : '' }} aria-label="تفعيل {{ $needType->name }}">@if($mandatory)<input type="hidden" name="execution_needs[{{ $needType->id }}][is_required]" value="1">@endif</div></div><div class="ramadan-need-details mt-3" {{ $enabled ? '' : 'hidden' }}><label class="form-label" for="need-details-{{ $needType->id }}">{{ __('ramadan_iftars.planning.planning_details') }}</label><textarea id="need-details-{{ $needType->id }}" class="form-control" name="execution_needs[{{ $needType->id }}][planned_details]" rows="2">{{ $selectedNeed['planned_details']??'' }}</textarea>@include('pages.events.ramadan._execution_need_details', ['needCode' => $needType->code, 'collections' => $collections, 'users' => $users, 'giftTypes' => $giftTypes])</div></div>
        @empty <div class="text-muted">{{ __('ramadan_iftars.empty.execution_needs') }}</div> @endforelse
        </div></div></div>
        @include('pages.events.ramadan._historic_needs')
        @include('pages.events.ramadan._planning_collections', ['collections'=>$collections,'mealItemTypes'=>$mealItemTypes,'users'=>$users,'beneficiarySegments'=>$beneficiarySegments,'collectionFilter'=> $executionNeedTypes->contains('code', 'volunteers') ? ['program_segments','volunteer_requirements'] : ['program_segments'],'includeMeals'=>false])
        <button class="btn btn-primary" type="submit">{{ __('ramadan_iftars.planning.save_draft') }}</button>
    </form>
</div>
<script>

(function () {
    var token=document.querySelector('meta[name="csrf-token"]')?.content;
    document.querySelectorAll('[data-reference-picker]').forEach(function (picker) {
        var search=picker.querySelector('[data-reference-search]'), id=picker.querySelector('[data-reference-id]'), results=picker.querySelector('[data-reference-results]'), create=picker.querySelector('[data-reference-create]'), panel=picker.querySelector('[data-reference-create-form]'), timer;
        function select(item) {
            id.value=item.id; search.value=item.name; results.classList.add('d-none'); create.classList.add('d-none');
            ['contact_name','contact_phone','location_name','address','google_maps_url'].forEach(function(field){ var target=document.querySelector('[name="'+field+'"]'); if(target && item[field]) target.value=item[field]; });
        }
        search.addEventListener('input', function () {
            id.value=''; clearTimeout(timer); var term=search.value.trim();
            if(term.length<2){ results.classList.add('d-none'); create.classList.add('d-none'); return; }
            timer=setTimeout(function(){ fetch(picker.dataset.searchUrl+'?q='+encodeURIComponent(term), {headers:{'Accept':'application/json'}}).then(function(r){return r.json()}).then(function(body){
                results.innerHTML=''; (body.data||[]).forEach(function(item){ var button=document.createElement('button'); button.type='button'; button.className='list-group-item list-group-item-action'; button.textContent=item.label; button.addEventListener('click',function(){select(item)}); results.appendChild(button); });
                results.classList.toggle('d-none', !(body.data||[]).length); create.classList.toggle('d-none', (body.data||[]).length>0); create.querySelector('[data-reference-name]').textContent=term; picker.querySelector('[data-create-field="name"]').value=term;
            }); },250);
        });
        create.addEventListener('click',function(){ panel.classList.remove('d-none'); results.classList.add('d-none'); });
        picker.querySelector('[data-reference-cancel]').addEventListener('click',function(){panel.classList.add('d-none')});
        picker.querySelector('[data-reference-save]').addEventListener('click',function(){
            var payload={}; picker.querySelectorAll('[data-create-field]').forEach(function(input){payload[input.dataset.createField]=input.value});
            fetch(picker.dataset.createUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify(payload)}).then(async function(response){var body=await response.json(); if(!response.ok) throw body; return body}).then(function(item){select(item);panel.classList.add('d-none')}).catch(function(error){picker.querySelector('[data-reference-error]').textContent=error.errors?.name?.[0]||'تعذر حفظ الجهة.'});
        });
    });
})();

document.addEventListener('click', function (event) {
    if (event.target.matches('.remove-row')) event.target.closest('.planning-row').remove();
    if (event.target.matches('.add-row')) {
        var card=event.target.closest('[data-repeat]'), source=card.querySelector('.planning-row');
        if (!source) return;
        var clone=source.cloneNode(true), index=Date.now();
        clone.querySelectorAll('[name]').forEach(function (input) {
            input.name=input.name.replace(/\[\d+\]/,'['+index+']');
            if (input.type!=='hidden' && input.tagName!=='SELECT') input.value='';
            if (input.type==='hidden') input.value='';
        });
        card.querySelector('.card-body').appendChild(clone);
    }
});
</script>
