@extends('layouts.app')
@section('content')
@php
    $attendees = $ramadanIftar->attendees->concat([new \App\Modules\Events\Models\RamadanIftarAttendee]);
@endphp
<div class="container py-4">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('events.ramadan.iftars.index') }}">{{ __('ramadan_iftars.navigation.title') }}</a></li><li class="breadcrumb-item"><a href="{{ route('events.ramadan.iftars.show',$ramadanIftar) }}">{{ __('ramadan_iftars.navigation.workspace',['id'=>$ramadanIftar->id]) }}</a></li><li class="breadcrumb-item active" aria-current="page">{{ __('ramadan_iftars.titles.execution') }}</li></ol></nav>
    <div class="d-flex justify-content-between"><h1 class="h3">{{ __('ramadan_iftars.titles.execution') }}</h1><a href="{{ route('events.ramadan.iftars.show', $ramadanIftar) }}">{{ __('ramadan_iftars.actions.back') }}</a></div>
    <p class="text-muted">{{ __('ramadan_iftars.execution.private_hint',['title'=>$ramadanIftar->title]) }} · {{ optional($ramadanIftar->branch)->name }}</p>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.approved_baseline') }}</div><div class="card-body row">
        <div class="col-md-4"><strong>{{ __('ramadan_iftars.fields.planned_date') }}</strong><br>{{ optional($ramadanIftar->planned_date)->format('Y-m-d') }}</div>
        <div class="col-md-4"><strong>{{ __('ramadan_iftars.sections.attendance') }}</strong><br>{{ $ramadanIftar->expected_attendance }}</div>
        <div class="col-md-4"><strong>{{ __('ramadan_iftars.sections.meals') }}</strong><br>{{ $ramadanIftar->planned_meals_count }}</div>
    </div></div>

    @if($ramadanIftar->execution_status === \App\Modules\Events\Models\RamadanIftar::EXECUTION_STATUS_PLANNED)
        <form method="POST" action="{{ route('events.ramadan.iftars.execution.start', $ramadanIftar) }}">@csrf<button class="btn btn-primary">{{ __('ramadan_iftars.actions.start_execution') }}</button></form>
    @else
    <form method="POST" action="{{ route('events.ramadan.iftars.execution.update', $ramadanIftar) }}">@csrf @method('PUT')
        <fieldset @if(!$executionWritable) disabled @endif>
        <div class="card my-3"><div class="card-header">{{ __('ramadan_iftars.execution.actual_results') }}</div><div class="card-body">
            <label>{{ __('ramadan_iftars.fields.actual_date') }}</label><input class="form-control" type="date" name="actual_date" value="{{ old('actual_date', optional($ramadanIftar->actual_date)->format('Y-m-d')) }}">
            <small class="text-muted">{{ __('ramadan_iftars.execution.derived_hint') }}</small>
        </div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.attendance_roster') }}</div><div class="card-body">
        @if($ramadanIftar->attendees->isEmpty())<p class="text-muted">{{ __('ramadan_iftars.empty.attendees') }}</p>@endif
        @foreach($attendees as $i => $attendee)<div class="row g-2 border rounded p-2 mb-2">
            @if($attendee->exists)<input type="hidden" name="attendees[{{ $i }}][id]" value="{{ $attendee->id }}">@endif
            <div class="col-md-3"><input class="form-control" name="attendees[{{ $i }}][full_name]" value="{{ old("attendees.$i.full_name", $attendee->full_name) }}" placeholder="{{ __('ramadan_iftars.labels.full_name') }}"></div>
            <div class="col-md-2"><input class="form-control" name="attendees[{{ $i }}][phone]" value="{{ old("attendees.$i.phone", $attendee->phone) }}" placeholder="{{ __('ramadan_iftars.fields.phone') }}"></div>
            <div class="col-md-1"><input class="form-control" type="number" min="0" max="150" name="attendees[{{ $i }}][age]" value="{{ old("attendees.$i.age", $attendee->age) }}" placeholder="{{ __('ramadan_iftars.fields.age') }}"></div>
            <div class="col-md-2"><select class="form-select" name="attendees[{{ $i }}][target_group_id]"><option value="">{{ __('ramadan_iftars.labels.target_group') }}</option>@foreach($targetGroups as $group)<option value="{{ $group->id }}" @if($attendee->target_group_id == $group->id) selected @endif>{{ $group->name }}</option>@endforeach</select></div>
            <div class="col-md-2"><select class="form-select" name="attendees[{{ $i }}][beneficiary_segment_id]"><option value="">{{ __('ramadan_iftars.labels.beneficiary_segment') }}</option>@foreach($beneficiarySegments as $segment)<option value="{{ $segment->id }}" @if($attendee->beneficiary_segment_id == $segment->id) selected @endif>{{ app()->getLocale()==='ar' ? $segment->name_ar : ($segment->name_en ?: $segment->name_ar) }}</option>@endforeach</select></div>
            <div class="col-md-2"><input type="hidden" name="attendees[{{ $i }}][attended]" value="0"><label><input type="checkbox" name="attendees[{{ $i }}][attended]" value="1" @if(old("attendees.$i.attended", $attendee->attended)) checked @endif> {{ __('ramadan_iftars.labels.check_in') }}</label></div>
            <div class="col-md-3"><input class="form-control" name="attendees[{{ $i }}][notes]" value="{{ old("attendees.$i.notes", $attendee->notes) }}" placeholder="{{ __('ramadan_iftars.fields.notes') }}"></div>
            <div class="col-md-1">@if($attendee->exists)<label><input type="checkbox" name="attendees[{{ $i }}][_delete]" value="1"> {{ __('ramadan_iftars.planning.remove') }}</label>@endif</div>
        </div>@endforeach
        </div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.meals_gifts') }} — {{ __('ramadan_iftars.fields.expected') }} / {{ __('ramadan_iftars.fields.actual') }}</div><div class="card-body">
            @foreach($ramadanIftar->meals as $i => $meal)<input type="hidden" name="meals[{{ $i }}][id]" value="{{ $meal->id }}"><div class="row g-2 mb-2"><div class="col-md-4">{{ $meal->description }} ({{ __('ramadan_iftars.fields.expected') }}: {{ $meal->planned_quantity }})</div><div class="col-md-2"><input class="form-control" type="number" min="0" name="meals[{{ $i }}][actual_quantity]" value="{{ $meal->actual_quantity }}" placeholder="{{ __('ramadan_iftars.fields.actual') }}"></div><div class="col-md-2"><input class="form-control" type="number" min="1" max="5" name="meals[{{ $i }}][rating]" value="{{ $meal->rating }}" placeholder="{{ __('ramadan_iftars.labels.meal_rating') }}"></div><div class="col-md-4"><input class="form-control" name="meals[{{ $i }}][rating_notes]" value="{{ $meal->rating_notes }}" placeholder="{{ __('ramadan_iftars.labels.rating_notes') }}"></div></div>@endforeach
            @foreach($ramadanIftar->gifts as $i => $gift)<input type="hidden" name="gifts[{{ $i }}][id]" value="{{ $gift->id }}"><div class="row g-2 mb-2"><div class="col-md-6">{{ $gift->description }} ({{ __('ramadan_iftars.fields.expected') }}: {{ $gift->planned_quantity }})</div><div class="col-md-3"><input class="form-control" type="number" min="0" name="gifts[{{ $i }}][actual_quantity]" value="{{ $gift->actual_quantity }}" placeholder="{{ __('ramadan_iftars.labels.actual_quantity') }}"></div></div>@endforeach
            @if($ramadanIftar->meals->isEmpty() && $ramadanIftar->gifts->isEmpty())<p class="text-muted mb-0">{{ __('ramadan_iftars.empty.meals') }} {{ __('ramadan_iftars.empty.gifts') }}</p>@endif
        </div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.program_results') }}</div><div class="card-body">@forelse($ramadanIftar->programSegments as $i => $segment)<input type="hidden" name="program_segments[{{ $i }}][id]" value="{{ $segment->id }}"><div class="row g-2 mb-2"><div class="col-md-4">{{ $segment->name }}</div><div class="col-md-3"><select class="form-select" name="program_segments[{{ $i }}][execution_status]">@foreach(\App\Modules\Events\Models\RamadanIftarProgramSegment::statuses() as $status)<option value="{{ $status }}" @if($segment->execution_status === $status) selected @endif>{{ __('ramadan_iftars.statuses.execution.'.$status) }}</option>@endforeach</select></div><div class="col-md-5"><input class="form-control" name="program_segments[{{ $i }}][actual_notes]" value="{{ $segment->actual_notes }}" placeholder="{{ __('ramadan_iftars.labels.actual_notes') }}"></div></div>@empty<p class="text-muted mb-0">{{ __('ramadan_iftars.empty.programs') }}</p>@endforelse</div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.teams_tasks') }}</div><div class="card-body">@forelse($ramadanIftar->executionTeams as $i => $team)<input type="hidden" name="execution_teams[{{ $i }}][id]" value="{{ $team->id }}"><div class="border rounded p-2 mb-2"><div class="row"><div class="col-md-6"><strong>{{ $team->name }}</strong> ({{ __('ramadan_iftars.fields.expected') }}: {{ $team->planned_members_count ?: '—' }})</div><div class="col-md-3"><input class="form-control" type="number" min="0" name="execution_teams[{{ $i }}][actual_members_count]" value="{{ $team->actual_members_count }}" placeholder="{{ __('ramadan_iftars.labels.actual_members') }}"></div></div>@foreach($team->members as $j => $member)<input type="hidden" name="execution_teams[{{ $i }}][members][{{ $j }}][id]" value="{{ $member->id }}"><div class="row g-2 mt-2"><div class="col-md-4">{{ $member->member_name ?: optional($member->user)->name }}</div><div class="col-md-3"><select class="form-select" name="execution_teams[{{ $i }}][members][{{ $j }}][task_completed]"><option value="">{{ __('ramadan_iftars.execution.not_evaluated') }}</option><option value="1" @if($member->task_completed === true) selected @endif>{{ __('ramadan_iftars.execution.task_completed') }}</option><option value="0" @if($member->task_completed === false) selected @endif>{{ __('ramadan_iftars.execution.task_not_completed') }}</option></select></div><div class="col-md-5"><input class="form-control" name="execution_teams[{{ $i }}][members][{{ $j }}][actual_task_note]" value="{{ $member->actual_task_note }}" placeholder="{{ __('ramadan_iftars.labels.actual_task_note') }}"></div></div>@endforeach</div>@empty<p class="text-muted mb-0">{{ __('ramadan_iftars.empty.teams') }}</p>@endforelse</div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.execution.volunteers_supplies') }}</div><div class="card-body">@foreach($ramadanIftar->volunteerRequirements as $i => $row)<input type="hidden" name="volunteer_requirements[{{ $i }}][id]" value="{{ $row->id }}"><div class="row g-2 mb-2"><div class="col-md-6">{{ __('ramadan_iftars.sections.volunteers') }} — {{ __('ramadan_iftars.fields.expected') }}: {{ $row->planned_count }}</div><div class="col-md-3"><input class="form-control" type="number" min="0" name="volunteer_requirements[{{ $i }}][actual_count]" value="{{ $row->actual_count }}" placeholder="{{ __('ramadan_iftars.fields.actual') }}"></div></div>@endforeach @foreach($ramadanIftar->supplies as $i => $row)<input type="hidden" name="supplies[{{ $i }}][id]" value="{{ $row->id }}"><div class="row g-2 mb-2"><div class="col-md-4">{{ $row->item_name }} ({{ __('ramadan_iftars.fields.expected') }}: {{ $row->planned_quantity }})</div><div class="col-md-3"><input class="form-control" type="number" min="0" name="supplies[{{ $i }}][actual_quantity]" value="{{ $row->actual_quantity }}" placeholder="{{ __('ramadan_iftars.fields.actual') }}"></div><div class="col-md-3"><select class="form-select" name="supplies[{{ $i }}][is_available]"><option value="">{{ __('ramadan_iftars.execution.not_assessed') }}</option><option value="1" @if($row->is_available === true) selected @endif>{{ __('ramadan_iftars.execution.available') }}</option><option value="0" @if($row->is_available === false) selected @endif>{{ __('ramadan_iftars.execution.unavailable') }}</option></select></div></div>@endforeach @if($ramadanIftar->volunteerRequirements->isEmpty() && $ramadanIftar->supplies->isEmpty())<p class="text-muted mb-0">{{ __('ramadan_iftars.empty.volunteers') }} {{ __('ramadan_iftars.empty.supplies') }}</p>@endif</div></div>

        <div class="card mb-3"><div class="card-header">{{ __('ramadan_iftars.sections.execution_needs') }}</div><div class="card-body">@forelse($ramadanIftar->executionNeeds as $i => $need)<input type="hidden" name="execution_needs[{{ $i }}][id]" value="{{ $need->id }}"><div class="row g-2 mb-2"><div class="col-md-4">{{ optional($need->executionNeedType)->name }} — {{ __('ramadan_iftars.statuses.requirement.'.($need->is_required ? 'required' : 'not_required')) }}<br><small>{{ $need->planned_details }}</small></div><div class="col-md-3"><select class="form-select" name="execution_needs[{{ $i }}][status]"><option value="pending" @if($need->status === 'pending') selected @endif>{{ __('ramadan_iftars.statuses.execution.pending') }}</option><option value="completed" @if($need->status === 'completed') selected @endif>{{ __('ramadan_iftars.execution.task_completed') }}</option></select></div><div class="col-md-5"><input class="form-control" name="execution_needs[{{ $i }}][actual_details]" value="{{ $need->actual_details }}" placeholder="{{ __('ramadan_iftars.labels.execution_need_result') }}"></div></div>@empty<p class="text-muted mb-0">{{ __('ramadan_iftars.empty.execution_needs') }}</p>@endforelse</div></div>
        @if($executionWritable)<button class="btn btn-success">{{ __('ramadan_iftars.actions.save_actual') }}</button>@endif
        </fieldset>
    </form>
    @endif
</div>
@endsection
