@extends('layouts.app')
@section('content')
<div class="container py-4">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item active" aria-current="page">{{ __('ramadan_iftars.navigation.title') }}</li></ol></nav>
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
        <div><h1 class="h3 mb-1">{{ __('ramadan_iftars.titles.index') }}</h1><p class="text-muted mb-0">{{ __('ramadan_iftars.sections.lifecycle') }}</p></div>
        <div class="d-flex flex-wrap gap-2">
            @can('ramadan_iftars.approve')<a class="btn btn-outline-primary" href="{{ route('events.ramadan.approvals.index') }}">{{ __('ramadan_iftars.navigation.approvals') }}</a>@endcan
            @can('ramadan_iftars.monitor.review')<a class="btn btn-outline-dark" href="{{ route('events.ramadan.monitoring-reviews.index') }}">{{ __('ramadan_iftars.navigation.monitoring_reviews') }}</a>@endcan
            @can('ramadan_iftars.create')<a class="btn btn-primary" href="{{ route('events.ramadan.iftars.create') }}">{{ __('ramadan_iftars.actions.create') }}</a>@endcan
        </div>
    </div>
    <form method="GET" class="card shadow-sm mb-4"><div class="card-body"><div class="row g-3 align-items-end">
        <div class="col-lg-3"><label class="form-label" for="ramadan-search">{{ __('ramadan_iftars.filters.search') }}</label><input id="ramadan-search" class="form-control" name="search" value="{{ $filters['search'] ?? '' }}"></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-branch">{{ __('ramadan_iftars.fields.branch') }}</label><select id="ramadan-branch" class="form-select" name="branch_id"><option value="">{{ __('ramadan_iftars.filters.all_branches') }}</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(($filters['branch_id'] ?? '') == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-plan-status">{{ __('ramadan_iftars.fields.planning_status') }}</label><select id="ramadan-plan-status" class="form-select" name="status"><option value="">{{ __('ramadan_iftars.filters.all_planning') }}</option>@foreach(['draft','submitted','changes_requested','approved'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.planning.'.$status) }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-execution-status">{{ __('ramadan_iftars.fields.execution_status') }}</label><select id="ramadan-execution-status" class="form-select" name="execution_status"><option value="">{{ __('ramadan_iftars.filters.all_execution') }}</option>@foreach(['planned','in_progress','completed'] as $status)<option value="{{ $status }}" @selected(($filters['execution_status'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.execution.'.$status) }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-closure">{{ __('ramadan_iftars.fields.closure_status') }}</label><select id="ramadan-closure" class="form-select" name="closure"><option value="">{{ __('ramadan_iftars.filters.all_closure') }}</option>@foreach(['open','closed'] as $status)<option value="{{ $status }}" @selected(($filters['closure'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.closure.'.$status) }}</option>@endforeach</select></div>
        <div class="col-lg-1 d-flex gap-2"><button class="btn btn-primary" title="{{ __('ramadan_iftars.actions.filter') }}"><i class="fas fa-filter" aria-hidden="true"></i><span class="visually-hidden">{{ __('ramadan_iftars.actions.filter') }}</span></button><a class="btn btn-outline-secondary" href="{{ route('events.ramadan.iftars.index') }}" title="{{ __('ramadan_iftars.actions.reset') }}"><i class="fas fa-rotate-left" aria-hidden="true"></i><span class="visually-hidden">{{ __('ramadan_iftars.actions.reset') }}</span></a></div>
    </div></div></form>
    <div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
        <thead class="table-light"><tr><th>{{ __('ramadan_iftars.fields.title') }}</th><th>{{ __('ramadan_iftars.fields.branch') }}</th><th>{{ __('ramadan_iftars.fields.planned_date') }}</th><th>{{ __('ramadan_iftars.fields.relations_officer') }}</th><th>{{ __('ramadan_iftars.fields.planning_status') }}</th><th>{{ __('ramadan_iftars.fields.execution_status') }}</th><th>{{ __('ramadan_iftars.fields.monitoring_status') }}</th><th>{{ __('ramadan_iftars.fields.closure_status') }}</th><th>{{ __('ramadan_iftars.fields.actions') }}</th></tr></thead>
        <tbody>@forelse($iftars as $iftar)@php($monitoring = $iftar->monitoringReports->first())<tr>
            <td><a class="fw-semibold text-decoration-none" href="{{ route('events.ramadan.iftars.show', $iftar) }}">{{ $iftar->title }}</a><div class="small text-muted">#{{ $iftar->id }}</div></td><td>{{ optional($iftar->branch)->name }}</td><td>{{ optional($iftar->planned_date)->format('Y-m-d') ?: '—' }}</td><td>{{ optional($iftar->relationsOfficer)->name ?: '—' }}</td>
            <td><span class="badge bg-secondary">{{ __('ramadan_iftars.statuses.planning.'.$iftar->status) }}</span></td><td><span class="badge bg-info text-dark">{{ __('ramadan_iftars.statuses.execution.'.$iftar->execution_status) }}</span></td><td>@if($monitoring)<span class="badge bg-primary">{{ __('ramadan_iftars.statuses.monitoring.'.$monitoring->status) }}</span>@else<span class="text-muted">—</span>@endif</td><td><span class="badge {{ $iftar->closed_at ? 'bg-dark' : 'bg-light text-dark border' }}">{{ __('ramadan_iftars.statuses.closure.'.($iftar->closed_at ? 'closed' : 'open')) }}</span></td>
            <td><a class="btn btn-sm btn-outline-primary" href="{{ route('events.ramadan.iftars.show', $iftar) }}">{{ __('ramadan_iftars.actions.view') }}</a></td>
        </tr>@empty<tr><td colspan="9" class="text-center text-muted py-5">{{ __('ramadan_iftars.empty.iftars') }}</td></tr>@endforelse</tbody>
    </table></div></div><div class="mt-3">{{ $iftars->links() }}</div>
</div>
@endsection
