@extends('layouts.app')
@section('content')
<div class="container py-4">
    <div class="card ramadan-hero shadow-sm mb-4"><div class="card-body p-4 d-flex flex-wrap justify-content-between align-items-center gap-3">
        <div><div class="small opacity-75">مساحة التخطيط والتنفيذ والمتابعة</div><h1 class="h3 mb-1">{{ __('ramadan_iftars.titles.index') }}</h1><p class="mb-0 opacity-75">رؤية موحدة لمسار كل إفطار من المسودة حتى الإغلاق</p></div>
        <div class="d-flex flex-wrap gap-2 ramadan-no-print">
            <div class="btn-group" role="group" aria-label="نوع العرض"><a class="btn btn-light active" href="{{ route('events.ramadan.iftars.index',request()->query()) }}"><i class="fas fa-grip"></i> بطاقات</a><a class="btn btn-outline-light" href="{{ route('events.ramadan.iftars.calendar') }}"><i class="fas fa-calendar-days"></i> تقويم</a></div>
            @can('ramadan_iftars.approve')<a class="btn btn-outline-light" href="{{ route('events.ramadan.approvals.index') }}">{{ __('ramadan_iftars.navigation.approvals') }}</a>@endcan
            @can('ramadan_iftars.monitor.review')<a class="btn btn-outline-light" href="{{ route('events.ramadan.monitoring-reviews.index') }}">{{ __('ramadan_iftars.navigation.monitoring_reviews') }}</a>@endcan
            @can('ramadan_iftars.create')<a class="btn btn-warning" href="{{ route('events.ramadan.iftars.create') }}"><i class="fas fa-plus"></i> {{ __('ramadan_iftars.actions.create') }}</a>@endcan
        </div>
    </div></div>
    <form method="GET" class="card shadow-sm mb-4 ramadan-no-print"><div class="card-body"><div class="row g-3 align-items-end">
        <div class="col-lg-3"><label class="form-label" for="ramadan-search">{{ __('ramadan_iftars.filters.search') }}</label><input id="ramadan-search" class="form-control" name="search" value="{{ $filters['search'] ?? '' }}"></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-branch">{{ __('ramadan_iftars.fields.branch') }}</label><select id="ramadan-branch" class="form-select" name="branch_id"><option value="">{{ __('ramadan_iftars.filters.all_branches') }}</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(($filters['branch_id'] ?? '') == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-plan-status">{{ __('ramadan_iftars.fields.planning_status') }}</label><select id="ramadan-plan-status" class="form-select" name="status"><option value="">{{ __('ramadan_iftars.filters.all_planning') }}</option>@foreach(['draft','submitted','changes_requested','approved'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.planning.'.$status) }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-execution-status">{{ __('ramadan_iftars.fields.execution_status') }}</label><select id="ramadan-execution-status" class="form-select" name="execution_status"><option value="">{{ __('ramadan_iftars.filters.all_execution') }}</option>@foreach(['planned','in_progress','completed'] as $status)<option value="{{ $status }}" @selected(($filters['execution_status'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.execution.'.$status) }}</option>@endforeach</select></div>
        <div class="col-sm-6 col-lg-2"><label class="form-label" for="ramadan-closure">{{ __('ramadan_iftars.fields.closure_status') }}</label><select id="ramadan-closure" class="form-select" name="closure"><option value="">{{ __('ramadan_iftars.filters.all_closure') }}</option>@foreach(['open','closed'] as $status)<option value="{{ $status }}" @selected(($filters['closure'] ?? '') === $status)>{{ __('ramadan_iftars.statuses.closure.'.$status) }}</option>@endforeach</select></div>
        <div class="col-lg-1 d-flex gap-2"><button class="btn btn-primary" title="{{ __('ramadan_iftars.actions.filter') }}"><i class="fas fa-filter"></i></button><a class="btn btn-outline-secondary" href="{{ route('events.ramadan.iftars.index') }}" title="{{ __('ramadan_iftars.actions.reset') }}"><i class="fas fa-rotate-left"></i></a></div>
    </div></div></form>
    <div class="row g-4">
    @forelse($iftars as $iftar) @php($monitoring=$iftar->monitoringReports->first())
        <div class="col-12 col-md-6 col-xl-4"><article class="card ramadan-card shadow-sm h-100"><div class="card-body d-flex flex-column">
            <div class="d-flex justify-content-between gap-2 mb-3"><div><div class="small text-muted">#{{ $iftar->id }} · الإصدار {{ $iftar->version_number }}</div><h2 class="h5 mb-0"><a class="text-decoration-none text-dark" href="{{ route('events.ramadan.iftars.show',$iftar) }}">{{ $iftar->title }}</a></h2></div><i class="fas fa-moon text-warning fs-4" aria-hidden="true"></i></div>
            <div class="row g-2 small mb-3"><div class="col-6"><i class="fas fa-building text-muted"></i> {{ optional($iftar->branch)->name ?: '—' }}</div><div class="col-6"><i class="fas fa-calendar text-muted"></i> {{ optional($iftar->planned_date)->format('Y-m-d') ?: '—' }}</div><div class="col-6"><i class="fas fa-users text-muted"></i> {{ $iftar->expected_attendance }}</div><div class="col-6"><i class="fas fa-handshake text-muted"></i> {{ $iftar->supporting_entity_name ?: '—' }}</div></div>
            <div class="d-flex flex-wrap gap-2 mb-3"><span class="ramadan-status ramadan-status--{{ $iftar->status }}">{{ __('ramadan_iftars.statuses.planning.'.$iftar->status) }}</span><span class="ramadan-status ramadan-status--{{ $iftar->execution_status }}">{{ __('ramadan_iftars.statuses.execution.'.$iftar->execution_status) }}</span>@if($monitoring)<span class="ramadan-status ramadan-status--{{ $monitoring->status }}">{{ __('ramadan_iftars.statuses.monitoring.'.$monitoring->status) }}</span>@endif @if($iftar->closed_at)<span class="ramadan-status bg-dark text-white">مغلق</span>@endif</div>
            <div class="mt-auto d-flex gap-2"><a class="btn btn-sm btn-primary flex-grow-1" href="{{ route('events.ramadan.iftars.show',$iftar) }}">{{ __('ramadan_iftars.actions.view') }}</a>@if($iftar->isPlanningEditable()) @can('ramadan_iftars.edit')<a class="btn btn-sm btn-outline-primary" href="{{ route('events.ramadan.iftars.edit',$iftar) }}">تعديل</a>@endcan @endif</div>
        </div></article></div>
    @empty <div class="col-12"><div class="card shadow-sm"><div class="card-body text-center py-5"><i class="fas fa-moon fs-1 text-warning mb-3"></i><h2 class="h5">{{ __('ramadan_iftars.empty.iftars') }}</h2>@can('ramadan_iftars.create')<a class="btn btn-primary mt-2" href="{{ route('events.ramadan.iftars.create') }}">{{ __('ramadan_iftars.actions.create') }}</a>@endcan</div></div></div> @endforelse
    </div><div class="mt-4">{{ $iftars->links() }}</div>
</div>
@endsection
