@extends('layouts.app')
@section('content')
@php $hostLabel = optional($ramadanIftar->communityOrganization)->name ?: optional($ramadanIftar->localCommunity)->name ?: $ramadanIftar->host_type; @endphp
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h3 mb-1">{{ $ramadanIftar->title }}</h1><span class="badge bg-secondary">{{ $ramadanIftar->status }}</span> <span class="badge bg-info text-dark">{{ $ramadanIftar->execution_status }}</span></div><div class="d-flex gap-2">
        @if($canPlan)<a class="btn btn-outline-primary" href="{{ route('events.ramadan.iftars.edit', $ramadanIftar) }}">Edit plan</a>@endif
        @if($canSubmit)<form method="POST" action="{{ route('events.ramadan.iftars.submit', $ramadanIftar) }}">@csrf<button class="btn btn-primary">{{ $ramadanIftar->status === 'changes_requested' ? 'Resubmit' : 'Submit' }}</button></form>@endif
        @if($canCurrentUserApprove)<a class="btn btn-warning" href="{{ route('events.ramadan.approvals.show', $ramadanIftar) }}">Review approval</a>@endif
        @if($canExecute)<a class="btn btn-success" href="{{ route('events.ramadan.iftars.execution.show', $ramadanIftar) }}">{{ $ramadanIftar->execution_status === 'planned' ? 'Start execution' : 'View execution' }}</a>@endif
        @if($canCompleteExecution)<form method="POST" action="{{ route('events.ramadan.iftars.execution.complete', $ramadanIftar) }}">@csrf<button class="btn btn-outline-success">Complete execution</button></form>@endif
        @if($canMonitor)<a class="btn btn-dark" href="{{ route('events.ramadan.iftars.monitoring.index', $ramadanIftar) }}">Monitoring</a>@endif
    </div></div>
    <div class="card mb-3"><div class="card-header">Core planning</div><div class="card-body row g-3">
        @foreach(['Branch'=>optional($ramadanIftar->branch)->name,'Agenda'=>optional($ramadanIftar->agendaEvent)->event_name,'Relations officer'=>optional($ramadanIftar->relationsOfficer)->name,'Planned date'=>optional($ramadanIftar->planned_date)->format('Y-m-d'),'Time'=>trim($ramadanIftar->time_from.' – '.$ramadanIftar->time_to,' –'),'Location'=>$ramadanIftar->location_name ?: $ramadanIftar->location_type,'Address'=>$ramadanIftar->address,'Host'=>$hostLabel,'Contact'=>trim($ramadanIftar->contact_name.' '.$ramadanIftar->contact_phone),'Supporting entity'=>$ramadanIftar->supporting_entity_name,'Mobilization'=>optional($ramadanIftar->mobilizationMethod)->name_en] as $label=>$value)<div class="col-md-4"><strong>{{ $label }}</strong><br>{{ $value ?: '—' }}</div>@endforeach
    </div></div>
    <div class="card mb-3"><div class="card-header">Guidance</div><div class="card-body">{{ optional($ramadanIftar->guidanceVersion)->title ?? '—' }} · version {{ optional($ramadanIftar->guidanceVersion)->version_number ?? '—' }} · accepted {{ optional($ramadanIftar->guidance_accepted_at)->format('Y-m-d H:i') ?? '—' }}</div></div>
    <div class="row">
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Targeting (expected {{ $ramadanIftar->expected_attendance }})</div><ul class="list-group list-group-flush">@forelse($ramadanIftar->targetGroupSelections as $row)<li class="list-group-item">{{ optional($row->targetGroup)->name }} / {{ optional($row->beneficiarySegment)->name_en }} — {{ $row->planned_count }}</li>@empty<li class="list-group-item text-muted">None</li>@endforelse</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Execution Needs</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->executionNeeds as $row)<li class="list-group-item"><strong>{{ optional($row->executionNeedType)->name }}</strong> · {{ $row->is_required ? 'Required' : 'Not required' }} · {{ $row->status }}<br><small>Plan: {{ $row->planned_details ?: '—' }} | Actual: {{ $row->actual_details ?: '—' }}</small></li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Meals (actual {{ $ramadanIftar->actual_meals_count ?? '—' }} / planned {{ $ramadanIftar->planned_meals_count }})</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->meals as $row)<li class="list-group-item">{{ $row->description }} — {{ $row->actual_quantity ?? '—' }} / {{ $row->planned_quantity }} · {{ $row->source_name ?: $row->source_type ?: '—' }} @if($row->rating)· rating {{ $row->rating }}/5@endif</li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Gifts</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->gifts as $row)<li class="list-group-item">{{ $row->description }} — {{ $row->actual_quantity ?? '—' }} / {{ $row->planned_quantity }}</li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Program segments</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->programSegments as $row)<li class="list-group-item">{{ $row->name }} · {{ $row->starts_at }}–{{ $row->ends_at }} · {{ optional($row->executor)->name ?: $row->external_executor_name ?: '—' }} · {{ $row->execution_status }}<br><small>{{ $row->actual_notes }}</small></li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Teams</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->executionTeams as $team)<li class="list-group-item"><strong>{{ $team->name }}</strong> · leader {{ optional($team->leader)->name ?: '—' }} · {{ $team->actual_members_count ?? '—' }} / {{ $team->planned_members_count ?? '—' }} members<ul>@foreach($team->members as $member)<li>{{ $member->member_name ?: optional($member->user)->name }} — {{ is_null($member->task_completed) ? 'not evaluated' : ($member->task_completed ? 'completed' : 'not completed') }} {{ $member->actual_task_note }}</li>@endforeach</ul></li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Volunteers</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->volunteerRequirements as $row)<li class="list-group-item">{{ optional($row->beneficiarySegment)->name_en ?: 'All' }} — {{ $row->actual_count ?? '—' }} / {{ $row->planned_count }}</li>@endforeach</ul></div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">Supplies</div><ul class="list-group list-group-flush">@foreach($ramadanIftar->supplies as $row)<li class="list-group-item">{{ $row->item_name }} — {{ $row->actual_quantity ?? '—' }} / {{ $row->planned_quantity }} · {{ is_null($row->is_available) ? 'not assessed' : ($row->is_available ? 'available' : 'unavailable') }}</li>@endforeach</ul></div></div>
    </div>
    <div class="card mb-3"><div class="card-header">Attendance and closure</div><div class="card-body">Actual {{ $ramadanIftar->actual_attendance ?? '—' }} / expected {{ $ramadanIftar->expected_attendance }}. Detailed attendee data is restricted to the execution workspace.<br>Closure: @if($ramadanIftar->closed_at)<span class="badge bg-dark">Closed {{ $ramadanIftar->closed_at->format('Y-m-d H:i') }}</span>@else<span class="badge bg-light text-dark">Open</span>@endif</div></div>
    <div class="card mb-3"><div class="card-header">Workflow</div><div class="card-body"><p>Current step: {{ optional(optional($ramadanIftar->workflowInstance)->currentStep)->name_en ?? '—' }} · submitted {{ optional($ramadanIftar->submitted_at)->format('Y-m-d H:i') ?? '—' }} · approved {{ optional($ramadanIftar->approved_at)->format('Y-m-d H:i') ?? '—' }}</p><ul>@foreach(optional($ramadanIftar->workflowInstance)->logs ?? [] as $log)<li>{{ optional($log->step)->name_en }} — {{ $log->action }} by {{ optional($log->actor)->name }} @if($log->comment)· {{ $log->comment }}@endif</li>@endforeach</ul></div></div>
    <div class="card"><div class="card-header">Monitoring</div><ul class="list-group list-group-flush">@forelse($ramadanIftar->monitoringReports as $report)<li class="list-group-item">@if($canMonitor)<a href="{{ route('events.ramadan.iftars.monitoring.edit', [$ramadanIftar, $report]) }}">{{ optional($report->monitoringMethod)->name_en }}</a>@else{{ optional($report->monitoringMethod)->name_en }}@endif · {{ $report->status }} · {{ optional($report->observed_at)->format('Y-m-d H:i') }}</li>@empty<li class="list-group-item text-muted">No monitoring reports.</li>@endforelse</ul></div>
</div>
@endsection
