<?php

return [
    'navigation' => ['title' => 'الإفطارات الرمضانية', 'all' => 'كل الإفطارات', 'approvals' => 'اعتمادات الخطط', 'monitoring_reviews' => 'مراجعات المتابعة'],
    'titles' => ['index' => 'الإفطارات الرمضانية', 'show' => 'مساحة عمل الإفطار الرمضاني', 'guidance' => 'إرشادات الإفطار الرمضاني', 'create' => 'إنشاء إفطار رمضاني', 'edit' => 'تعديل خطة الإفطار الرمضاني', 'execution' => 'التنفيذ', 'monitoring' => 'المتابعة', 'monitoring_review' => 'مراجعة المتابعة', 'monitoring_review_queue' => 'قائمة مراجعة المتابعة'],
    'sections' => ['lifecycle' => 'دورة العمل', 'planning' => 'الخطة', 'core' => 'بيانات الخطة الأساسية', 'guidance' => 'الإرشادات', 'targeting' => 'الفئات المستهدفة', 'execution_needs' => 'احتياجات التنفيذ', 'meals' => 'الوجبات', 'gifts' => 'الهدايا', 'programs' => 'فقرات البرنامج', 'teams' => 'فرق التنفيذ', 'volunteers' => 'المتطوعون', 'supplies' => 'اللوازم', 'attendance' => 'الحضور', 'approval' => 'الاعتماد', 'workflow' => 'سير الاعتماد', 'monitoring' => 'المتابعة', 'closure' => 'الإغلاق', 'actual_event' => 'بيانات التنفيذ الفعلية', 'reports' => 'تقارير المتابعة', 'verifications' => 'التحققات الميدانية'],
    'actions' => ['create' => 'إنشاء إفطار رمضاني', 'edit' => 'تعديل الخطة', 'submit' => 'إرسال', 'resubmit' => 'إعادة الإرسال', 'approve' => 'اعتماد', 'return' => 'إعادة للتعديل', 'review_approval' => 'مراجعة الاعتماد', 'start_execution' => 'بدء التنفيذ', 'view_execution' => 'عرض التنفيذ', 'save_actual' => 'حفظ البيانات الفعلية', 'complete_execution' => 'إكمال التنفيذ', 'monitoring' => 'المتابعة', 'create_report' => 'إنشاء تقرير متابعة', 'submit_monitoring' => 'إرسال تقرير المتابعة', 'review_monitoring' => 'مراجعة المتابعة', 'save' => 'حفظ', 'back' => 'رجوع', 'accept_guidance' => 'قبول الإرشادات والمتابعة'],
    'statuses' => [
        'planning' => ['draft' => 'مسودة', 'submitted' => 'بانتظار الاعتماد', 'changes_requested' => 'معاد للتعديل', 'approved' => 'معتمد'],
        'execution' => ['planned' => 'مخطط', 'pending' => 'قيد الانتظار', 'cancelled' => 'ملغى', 'in_progress' => 'قيد التنفيذ', 'completed' => 'مكتمل'],
        'monitoring' => ['draft' => 'مسودة', 'submitted' => 'بانتظار المراجعة', 'returned' => 'معاد للتعديل', 'approved' => 'معتمد'],
        'verification' => ['matched' => 'مطابق', 'mismatched' => 'غير مطابق', 'not_observed' => 'لم يُرصد', 'not_applicable' => 'لا ينطبق'],
        'closure' => ['open' => 'مفتوح', 'closed' => 'مغلق'],
        'requirement' => ['required' => 'مطلوب', 'not_required' => 'غير مطلوب'],
    ],
    'fields' => ['id' => 'الرقم', 'title' => 'العنوان', 'branch' => 'الفرع', 'planned_date' => 'التاريخ المخطط', 'actual_date' => 'التاريخ الفعلي', 'relations_officer' => 'مسؤول العلاقات', 'planning_status' => 'حالة الخطة', 'execution_status' => 'حالة التنفيذ', 'monitoring_status' => 'حالة المتابعة', 'closure_status' => 'حالة الإغلاق', 'expected' => 'المخطط', 'actual' => 'الفعلي', 'variance' => 'الفرق', 'current_step' => 'خطوة الاعتماد الحالية', 'method' => 'طريقة المتابعة', 'monitor' => 'مسؤول المتابعة', 'submitted_at' => 'تاريخ الإرسال', 'observed_at' => 'تاريخ الرصد', 'notes' => 'الملاحظات', 'comment' => 'تعليق المراجعة', 'field' => 'الحقل', 'verification_status' => 'حالة التحقق', 'actions' => 'الإجراءات', 'phone' => 'الهاتف', 'age' => 'العمر', 'name' => 'الاسم'],
    'verification_fields' => ['attendance' => 'الحضور', 'meals' => 'الوجبات', 'date' => 'تاريخ الفعالية', 'meal' => 'وجبة: :name', 'gift' => 'هدية: :name', 'program' => 'فقرة: :name', 'team' => 'فريق: :name', 'volunteer' => 'متطلب متطوعين رقم :id', 'supply' => 'لوازم: :name', 'execution_need' => 'احتياج تنفيذ: :name'],
    'empty' => ['iftars' => 'لا توجد إفطارات رمضانية.', 'meals' => 'لا توجد وجبات.', 'gifts' => 'لا توجد هدايا.', 'programs' => 'لا توجد فقرات برنامج.', 'teams' => 'لا توجد فرق تنفيذ.', 'volunteers' => 'لا توجد متطلبات متطوعين.', 'supplies' => 'لا توجد لوازم.', 'monitoring' => 'لا توجد تقارير متابعة.', 'workflow' => 'لا يوجد سجل اعتماد.', 'verifications' => 'لا توجد تحققات ميدانية.', 'reviews' => 'لا توجد تقارير متابعة بانتظار المراجعة.'],
    'hints' => ['guidance_acceptance' => 'قرأت نسخة الإرشادات هذه وأوافق عليها.', 'version' => 'الإصدار :number', 'read_only_execution' => 'اكتمل التنفيذ وتعرض بياناته للقراءة فقط.', 'read_only_monitoring' => 'تعرض أدلة المتابعة للقراءة فقط.', 'attendance_private' => 'تفاصيل بيانات الحضور متاحة فقط في مساحة التنفيذ المحمية.', 'return_comment' => 'التعليق إلزامي عند إعادة التقرير للتعديل.', 'mismatch_documented' => 'يمكن اعتماد الاختلافات فقط عند توثيق ملاحظة لكل حالة غير مطابقة.'],
    'messages' => ['created' => 'تم إنشاء الإفطار الرمضاني.', 'updated' => 'تم تحديث الإفطار الرمضاني.', 'submitted' => 'تم إرسال الإفطار الرمضاني للاعتماد.', 'decision_recorded' => 'تم تسجيل قرار الاعتماد.', 'execution_started' => 'تم بدء تنفيذ الإفطار الرمضاني.', 'execution_updated' => 'تم حفظ بيانات التنفيذ الفعلية.', 'execution_completed' => 'تم إكمال تنفيذ الإفطار الرمضاني.', 'monitoring_created' => 'تم إنشاء تقرير المتابعة.', 'monitoring_updated' => 'تم تحديث تقرير المتابعة.', 'monitoring_submitted' => 'تم إرسال تقرير المتابعة.', 'monitoring_reviewed' => 'تم تسجيل قرار مراجعة المتابعة.', 'guidance_accepted' => 'تم قبول الإرشادات، ويمكن الآن إنشاء الإفطار الرمضاني.'],
    'errors' => ['review_not_authorized' => 'لا تملك صلاحية مراجعة تقرير المتابعة هذا.', 'review_submitted_only' => 'لا يمكن مراجعة إلا تقرير متابعة مرسل.', 'self_review' => 'لا يجوز لمسؤول المتابعة مراجعة تقريره بنفسه.', 'invalid_review_decision' => 'قرار مراجعة المتابعة غير صالح.', 'return_comment_required' => 'التعليق إلزامي عند إعادة التقرير.', 'mismatch_note_required' => 'يجب توثيق ملاحظة لكل تحقق غير مطابق قبل الاعتماد.'],
];
