@extends('layouts.app')
@section('page_title', 'إدارة إفطارات رمضان')
@section('content')
<div class="container py-4" dir="rtl">
<div class="mb-4"><h1 class="h3">إدارة إفطارات رمضان</h1><p class="text-muted">إدارة إعدادات ومراجع الإفطارات الرمضانية.</p></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>تعذر الحفظ:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<ul class="nav nav-tabs mb-4"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#settings">الإعدادات</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#mobilization">طرق الحشد والاستقطاب</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#gift-types">أنواع الهدايا والدروع</button></li></ul>
<div class="tab-content">
<section class="tab-pane fade show active" id="settings">
<div class="row g-4"><div class="col-12"><div class="card"><div class="card-header"><strong>فترات رمضان</strong></div><div class="card-body">
@if($activePeriod)<div class="alert alert-success">الفترة النشطة: {{ $activePeriod->year }} / {{ $activePeriod->hijri_year ?: 'السنة الهجرية غير مدخلة' }} — {{ $activePeriod->start_date->format('Y-m-d') }} إلى {{ $activePeriod->end_date->format('Y-m-d') }}</div>@else<div class="alert alert-warning">لا توجد فترة رمضان نشطة.</div>@endif
<form method="POST" action="{{ route('events.ramadan.admin.periods.store') }}" class="row g-2 mb-4">@csrf
<div class="col-md-2"><label class="form-label">السنة الميلادية</label><input class="form-control" type="number" name="year" value="{{ old('year') }}" required></div><div class="col-md-2"><label class="form-label">السنة الهجرية</label><input class="form-control" type="number" name="hijri_year" value="{{ old('hijri_year') }}" required></div><div class="col-md-3"><label class="form-label">البداية</label><input class="form-control" type="date" name="start_date" required></div><div class="col-md-3"><label class="form-label">النهاية</label><input class="form-control" type="date" name="end_date" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">إضافة فترة رمضان</button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>الميلادية</th><th>الهجرية</th><th>البداية</th><th>النهاية</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@foreach($periods as $period)<tr><form method="POST" action="{{ route('events.ramadan.admin.periods.update',$period) }}">@csrf @method('PUT')<td><input class="form-control" name="year" value="{{ $period->year }}"></td><td><input class="form-control" name="hijri_year" value="{{ $period->hijri_year }}" required></td><td><input class="form-control" type="date" name="start_date" value="{{ $period->start_date->format('Y-m-d') }}"></td><td><input class="form-control" type="date" name="end_date" value="{{ $period->end_date->format('Y-m-d') }}"></td><td><span class="badge {{ $period->is_active?'bg-success':'bg-secondary' }}">{{ $period->is_active?'نشط':'غير نشط' }}</span></td><td class="d-flex gap-1"><button class="btn btn-sm btn-outline-primary">تعديل</button></form><form method="POST" action="{{ route('events.ramadan.admin.periods.'.($period->is_active?'deactivate':'activate'),$period) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">{{ $period->is_active?'إلغاء التفعيل':'تفعيل' }}</button></form></td></tr>@endforeach</tbody></table></div>
</div></div></div>
<div class="col-12"><div class="card"><div class="card-header"><strong>الإرشادات والتعليمات</strong></div><div class="card-body">
@if($currentGuidance)<div class="alert alert-success">الإصدار الحالي: {{ $currentGuidance->version_number }} — {{ $currentGuidance->title }}</div>@else<div class="alert alert-warning">لا يوجد إصدار منشور نشط.</div>@endif
<form method="POST" action="{{ route('events.ramadan.admin.guidance.store') }}" class="mb-4">@csrf<div class="mb-2"><label class="form-label">العنوان</label><input class="form-control" name="title" required></div><div class="mb-2"><label class="form-label">المحتوى</label><textarea class="form-control" name="content" rows="5" required></textarea></div><button class="btn btn-primary">إنشاء مسودة إصدار جديد</button></form>
@foreach($guidanceVersions as $guidance)<div class="border rounded p-3 mb-2"><form method="POST" action="{{ route('events.ramadan.admin.guidance.update',$guidance) }}">@csrf @method('PUT')<div class="d-flex justify-content-between"><strong>الإصدار {{ $guidance->version_number }}</strong><span class="badge {{ $guidance->is_active?'bg-success':'bg-secondary' }}">{{ $guidance->is_active?'حالي':'غير نشط' }}</span></div><small class="text-muted">النشر: {{ $guidance->published_at?->format('Y-m-d H:i') ?: 'مسودة' }} | الإنشاء: {{ $guidance->created_at?->format('Y-m-d H:i') }} | التحديث: {{ $guidance->updated_at?->format('Y-m-d H:i') }}</small><input class="form-control my-2" name="title" value="{{ $guidance->title }}" {{ $guidance->published_at?'disabled':'' }}><textarea class="form-control mb-2" name="content" rows="4" {{ $guidance->published_at?'disabled':'' }}>{{ $guidance->content }}</textarea>@unless($guidance->published_at)<button class="btn btn-sm btn-outline-primary">حفظ المسودة</button>@endunless</form><div class="d-flex gap-1 mt-2">@unless($guidance->is_active)<form method="POST" action="{{ route('events.ramadan.admin.guidance.publish',$guidance) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-success">نشر وتفعيل</button></form>@else<form method="POST" action="{{ route('events.ramadan.admin.guidance.deactivate',$guidance) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">أرشفة</button></form>@endunless</div></div>@endforeach
</div></div></div></div></section>
<section class="tab-pane fade" id="mobilization"><div class="card"><div class="card-body"><form method="POST" action="{{ route('events.ramadan.admin.mobilization-methods.store') }}" class="row g-2 mb-4">@csrf<div class="col-md-2"><input class="form-control" name="code" placeholder="الكود" required></div><div class="col-md-3"><input class="form-control" name="name_ar" placeholder="الاسم العربي" required></div><div class="col-md-3"><input class="form-control" name="name_en" placeholder="الاسم الإنجليزي" required></div><div class="col-md-2"><input class="form-control" type="number" name="sort_order" value="0" required></div><input type="hidden" name="is_active" value="1"><div class="col-md-2"><button class="btn btn-primary">إضافة</button></div></form>
@foreach($mobilizationMethods as $method)<form method="POST" action="{{ route('events.ramadan.admin.mobilization-methods.update',$method) }}" class="row g-2 border-top py-2">@csrf @method('PUT')<div class="col-md-2"><code>{{ $method->code }}</code></div><div class="col-md-3"><input class="form-control" name="name_ar" value="{{ $method->name_ar }}"></div><div class="col-md-3"><input class="form-control" name="name_en" value="{{ $method->name_en }}"></div><div class="col-md-1"><input class="form-control" name="sort_order" value="{{ $method->sort_order }}"></div><input type="hidden" name="is_active" value="{{ $method->is_active?1:0 }}"><input type="hidden" name="is_other" value="{{ $method->is_other?1:0 }}"><div class="col-md-3 d-flex gap-1"><button class="btn btn-sm btn-outline-primary">حفظ</button></form><form method="POST" action="{{ route('events.ramadan.admin.mobilization-methods.toggle',$method) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">{{ $method->is_active?'تعطيل':'تفعيل' }}</button></form></div>@endforeach</div></div></section>
<section class="tab-pane fade" id="gift-types"><div class="card"><div class="card-body"><form method="POST" action="{{ route('events.ramadan.admin.gift-types.store') }}" class="row g-2 mb-4">@csrf<div class="col-md-3"><input class="form-control" name="code" placeholder="الكود" required></div><div class="col-md-4"><input class="form-control" name="name_ar" placeholder="الاسم العربي" required></div><div class="col-md-2"><input class="form-control" name="sort_order" type="number" value="0"></div><input type="hidden" name="is_active" value="1"><div class="col-md-3"><button class="btn btn-primary">إضافة</button></div></form>@foreach($giftTypes as $giftType)<div class="row g-2 border-top py-2"><div class="col-md-2"><code>{{ $giftType->code }}</code></div><div class="col-md-7"><form class="d-flex gap-2" method="POST" action="{{ route('events.ramadan.admin.gift-types.update',$giftType) }}">@csrf @method('PUT')<input class="form-control" name="name_ar" value="{{ $giftType->name_ar }}"><input class="form-control" type="number" name="sort_order" value="{{ $giftType->sort_order }}"><input type="hidden" name="is_active" value="{{ $giftType->is_active?1:0 }}"><button class="btn btn-outline-primary">حفظ</button></form></div><div class="col-md-3"><form method="POST" action="{{ route('events.ramadan.admin.gift-types.toggle',$giftType) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary">{{ $giftType->is_active?'تعطيل':'تفعيل' }}</button></form></div></div>@endforeach</div></div></section>
</div></div>
@endsection
