@extends('layouts.app')
@section('page_title', 'إدارة إفطارات رمضان')
@section('content')
<div class="container py-4" dir="rtl">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">إعدادات إفطارات رمضان</h1><p class="text-muted mb-0">فترات رمضان والإرشادات المنشورة فقط.</p></div><a class="btn btn-outline-success" href="{{ route('role.super_admin.ramadan_reference_data.index') }}">البيانات المرجعية</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>تعذر الحفظ:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="row g-4"><div class="col-12"><div class="card"><div class="card-header"><strong>فترات رمضان</strong></div><div class="card-body">
@if($activePeriod)<div class="alert alert-success">الفترة النشطة: {{ $activePeriod->year }} / {{ $activePeriod->hijri_year ?: 'السنة الهجرية غير مدخلة' }} — {{ $activePeriod->start_date->format('Y-m-d') }} إلى {{ $activePeriod->end_date->format('Y-m-d') }}</div>@else<div class="alert alert-warning">لا توجد فترة رمضان نشطة.</div>@endif
<form method="POST" action="{{ route('events.ramadan.admin.periods.sync') }}" class="row g-2 mb-4">@csrf<div class="col-md-4"><label class="form-label">السنة الميلادية للمقترح</label><input class="form-control" type="number" name="year" min="2020" max="2100" value="{{ now()->year + 1 }}" required></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-outline-success"><i class="fas fa-rotate"></i> مزامنة فترة رمضان</button></div><div class="col-12 form-text">الحساب اقتراح محلي عبر ICU/Umm al-Qura ولا يعتمد التواريخ أو يفعّلها تلقائيًا.</div></form>
<form method="POST" action="{{ route('events.ramadan.admin.periods.store') }}" class="row g-2 mb-4">@csrf
<div class="col-md-2"><label class="form-label">السنة الميلادية</label><input class="form-control" type="number" name="year" value="{{ old('year') }}" required></div><div class="col-md-2"><label class="form-label">السنة الهجرية</label><input class="form-control" type="number" name="hijri_year" value="{{ old('hijri_year') }}" required></div><div class="col-md-3"><label class="form-label">البداية</label><input class="form-control" type="date" name="start_date" required></div><div class="col-md-3"><label class="form-label">النهاية</label><input class="form-control" type="date" name="end_date" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">إضافة فترة رمضان</button></div></form>
@foreach($periods as $period)
<div class="border rounded p-3 mb-3">
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><strong>{{ $period->year }} ميلادي / {{ $period->hijri_year ?: '—' }} هجري</strong><div><span class="badge {{ $period->is_confirmed?'bg-info text-dark':'bg-warning text-dark' }}">{{ $period->is_confirmed?'تمت المراجعة':'مقترح' }}</span> <span class="badge {{ $period->is_active?'bg-success':'bg-secondary' }}">{{ $period->is_active?'نشط':'غير نشط' }}</span></div></div>
<div class="row g-2 small mb-3"><div class="col-md-3"><strong>المقترح:</strong> {{ $period->suggested_start_date?->format('Y-m-d') ?: '—' }} → {{ $period->suggested_end_date?->format('Y-m-d') ?: '—' }}</div><div class="col-md-3"><strong>المصدر:</strong> {{ $period->calculation_source ?: 'manual' }}</div><div class="col-md-3"><strong>آخر مزامنة:</strong> {{ $period->synced_at?->format('Y-m-d H:i') ?: '—' }}</div></div>
<form method="POST" action="{{ route('events.ramadan.admin.periods.update',$period) }}" class="row g-2">@csrf @method('PUT')
<div class="col-md-2"><label class="form-label">السنة الميلادية</label><input class="form-control" name="year" value="{{ $period->year }}"></div><div class="col-md-2"><label class="form-label">السنة الهجرية</label><input class="form-control" name="hijri_year" value="{{ $period->hijri_year }}" required></div><div class="col-md-3"><label class="form-label">البداية المعتمدة</label><input class="form-control operational-start" type="date" name="start_date" value="{{ $period->start_date->format('Y-m-d') }}"></div><div class="col-md-3"><label class="form-label">النهاية المعتمدة</label><input class="form-control operational-end" type="date" name="end_date" value="{{ $period->end_date->format('Y-m-d') }}"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary">حفظ التعديل</button></div>
<div class="col-12"><button type="button" class="btn btn-sm btn-light" onclick="this.closest('form').querySelectorAll('input[type=date]').forEach(i=>{let d=new Date(i.value+'T00:00:00');d.setDate(d.getDate()-1);i.value=d.toISOString().slice(0,10)})">-1 يوم</button> <button type="button" class="btn btn-sm btn-light" onclick="this.closest('form').querySelectorAll('input[type=date]').forEach(i=>{let d=new Date(i.value+'T00:00:00');d.setDate(d.getDate()+1);i.value=d.toISOString().slice(0,10)})">+1 يوم</button></div></form>
<div class="d-flex flex-wrap gap-1 mt-3">@if($period->suggested_start_date)<form method="POST" action="{{ route('events.ramadan.admin.periods.use-suggested',$period) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-info">استخدام التواريخ المقترحة</button></form>@endif @unless($period->is_confirmed)<form method="POST" action="{{ route('events.ramadan.admin.periods.confirm',$period) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-info">تأكيد المراجعة</button></form>@endunless <form method="POST" action="{{ route('events.ramadan.admin.periods.'.($period->is_active?'deactivate':'activate'),$period) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $period->is_active?'btn-outline-secondary':'btn-success' }}" {{ !$period->is_confirmed && !$period->is_active?'disabled':'' }}>{{ $period->is_active?'إلغاء التفعيل':'تفعيل' }}</button></form></div>
</div>
@endforeach
</div></div></div>
<div class="col-12"><div class="card"><div class="card-header"><strong>الإرشادات والتعليمات</strong></div><div class="card-body">
@if($currentGuidance)<div class="alert alert-success">الإصدار الحالي: {{ $currentGuidance->version_number }} — {{ $currentGuidance->title }}</div>@else<div class="alert alert-warning">لا يوجد إصدار منشور نشط.</div>@endif
<form method="POST" action="{{ route('events.ramadan.admin.guidance.store') }}" class="mb-4">@csrf<div class="mb-2"><label class="form-label">العنوان</label><input class="form-control" name="title" required></div><div class="mb-2"><label class="form-label">المحتوى</label><textarea class="form-control" name="content" rows="5" required></textarea></div><button class="btn btn-primary">إنشاء مسودة إصدار جديد</button></form>
@foreach($guidanceVersions as $guidance)<div class="border rounded p-3 mb-2"><form method="POST" action="{{ route('events.ramadan.admin.guidance.update',$guidance) }}">@csrf @method('PUT')<div class="d-flex justify-content-between"><strong>الإصدار {{ $guidance->version_number }}</strong><span class="badge {{ $guidance->is_active?'bg-success':'bg-secondary' }}">{{ $guidance->is_active?'حالي':'غير نشط' }}</span></div><small class="text-muted">النشر: {{ $guidance->published_at?->format('Y-m-d H:i') ?: 'مسودة' }} | الإنشاء: {{ $guidance->created_at?->format('Y-m-d H:i') }} | التحديث: {{ $guidance->updated_at?->format('Y-m-d H:i') }}</small><input class="form-control my-2" name="title" value="{{ $guidance->title }}" {{ $guidance->published_at?'disabled':'' }}><textarea class="form-control mb-2" name="content" rows="4" {{ $guidance->published_at?'disabled':'' }}>{{ $guidance->content }}</textarea>@unless($guidance->published_at)<button class="btn btn-sm btn-outline-primary">حفظ المسودة</button>@endunless</form><div class="d-flex gap-1 mt-2">@unless($guidance->is_active)<form method="POST" action="{{ route('events.ramadan.admin.guidance.publish',$guidance) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-success">نشر وتفعيل</button></form>@else<form method="POST" action="{{ route('events.ramadan.admin.guidance.deactivate',$guidance) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">أرشفة</button></form>@endunless</div></div>@endforeach
</div></div></div></div>
</div></div>
@endsection
