@extends('layouts.app')
@section('content')
@php
$report = $monitoringReport;
$verificationCounts = $report->verifications->countBy('match_status');
@endphp
<div class="container py-4">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('events.ramadan.iftars.index') }}">{{ __('ramadan_iftars.navigation.title') }}</a></li><li class="breadcrumb-item"><a href="{{ route('events.ramadan.monitoring-reviews.index') }}">{{ __('ramadan_iftars.navigation.monitoring_reviews') }}</a></li><li class="breadcrumb-item active" aria-current="page">#{{ $report->id }}</li></ol></nav>
    <div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><h1 class="h3 mb-1">{{ __('ramadan_iftars.titles.monitoring_review') }}</h1><p class="text-muted mb-0">{{ optional($report->ramadanIftar)->title }} · {{ optional(optional($report->ramadanIftar)->branch)->name }}</p></div><a class="btn btn-outline-secondary" href="{{ route('events.ramadan.monitoring-reviews.index') }}">{{ __('ramadan_iftars.actions.back') }}</a></div>
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row g-3 mb-4"><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ __('ramadan_iftars.fields.method') }}</small><div class="fw-semibold">{{ app()->getLocale()==='ar' ? optional($report->monitoringMethod)->name_ar : (optional($report->monitoringMethod)->name_en ?: optional($report->monitoringMethod)->name_ar) }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ __('ramadan_iftars.fields.monitor') }}</small><div class="fw-semibold">{{ optional($report->monitor)->name }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ __('ramadan_iftars.fields.observed_at') }}</small><div class="fw-semibold">{{ optional($report->observed_at)->format('Y-m-d H:i') ?: '—' }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ __('ramadan_iftars.fields.submitted_at') }}</small><div class="fw-semibold">{{ optional($report->submitted_at)->format('Y-m-d H:i') }}</div></div></div></div></div>
    <div class="row g-2 mb-4">@foreach(\App\Models\PostExecutionVerification::matchStatuses() as $status)<div class="col-6 col-lg-3"><div class="border rounded p-3 d-flex justify-content-between align-items-center"><span>{{ __('ramadan_iftars.statuses.verification.'.$status) }}</span><span class="badge bg-secondary">{{ $verificationCounts->get($status,0) }}</span></div></div>@endforeach</div>
    <div class="card shadow-sm mb-4"><div class="card-header fw-semibold">{{ __('ramadan_iftars.sections.verifications') }}</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>{{ __('ramadan_iftars.fields.field') }}</th><th>{{ __('ramadan_iftars.fields.expected') }}</th><th>{{ __('ramadan_iftars.fields.actual') }}</th><th>{{ __('ramadan_iftars.fields.verification_status') }}</th><th>{{ __('ramadan_iftars.fields.notes') }}</th></tr></thead><tbody>@forelse($report->verifications as $row)<tr><td>{{ $row->field_label }}</td><td>{{ data_get($row->planned_value, 'value', '—') }}</td><td>{{ data_get($row->actual_value, 'value', '—') }}</td><td><span class="badge bg-secondary">{{ __('ramadan_iftars.statuses.verification.'.$row->match_status) }}</span></td><td>{{ $row->note ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('ramadan_iftars.empty.verifications') }}</td></tr>@endforelse</tbody></table></div></div>
    <form method="POST" action="{{ route('events.ramadan.monitoring-reviews.decision', $report) }}">@csrf<div class="card shadow-sm"><div class="card-body"><label class="form-label" for="monitoring-review-comment">{{ __('ramadan_iftars.fields.comment') }}</label><textarea id="monitoring-review-comment" class="form-control mb-2" name="comment" rows="3">{{ old('comment') }}</textarea><small class="text-muted d-block mb-3">{{ __('ramadan_iftars.hints.return_comment') }}</small><div class="d-flex flex-wrap justify-content-end gap-2"><button class="btn btn-outline-warning" name="decision" value="returned">{{ __('ramadan_iftars.actions.return') }}</button><button class="btn btn-success" name="decision" value="approved">{{ __('ramadan_iftars.actions.approve') }}</button></div></div></div></form>
</div>
@endsection
